-- 015_vivc_variety_catalog.sql
-- Import European variety catalog from VIVC (vivc.de)
-- Source: Vitis International Variety Catalogue (JKI, Julius Kühn-Institut)
-- Total: 1,240 unique varieties + 11 curated seed = 1,251 total
-- PIWI: 49 detected via INTERSPECIFIC CROSS species field
-- Strategy: TRUNCATE + bulk INSERT + re-run seed for curated additions

-- Run in two steps:
--   1. psql -f db/migrations/015_vivc_variety_catalog.sql
--   2. psql -f db/seeds/001_varieties.sql
TRUNCATE varieties CASCADE;

INSERT INTO varieties (name, synonyms, piwi, color, origin_country, status) VALUES
  ('ABBUOTO', NULL, false, 'red', 'Italy', 'approved'),
  ('ABONDANT', NULL, false, 'white', 'France', 'approved'),
  ('ABOURIOU', NULL, false, 'red', 'France', 'approved'),
  ('ABRUSCO', NULL, false, 'red', 'Italy', 'approved'),
  ('ACCENT', NULL, false, 'red', 'Germany', 'approved'),
  ('ACOLON', NULL, false, 'red', 'Germany', 'approved'),
  ('AFFENTHALER', ARRAY['AFFENTHALER'], false, 'red', NULL, 'approved'),
  ('AFUS ALI', ARRAY['KERINO'], false, 'other', 'Greece', 'approved'),
  ('AGIANNIOTIKO', NULL, false, 'red', 'Greece', 'approved'),
  ('AGIORGITIKO', ARRAY['MAVRO NEMEAS*'], false, 'red', 'Greece', 'approved'),
  ('AGLIANICO', NULL, false, 'red', 'Bulgaria', 'approved'),
  ('AGNI', NULL, false, 'red', 'Czech Republic', 'approved'),
  ('AGOUMASTOS KOKKINO', NULL, false, 'white', 'Greece', 'approved'),
  ('AGRIOGLYKADA', NULL, false, 'white', 'Greece', 'approved'),
  ('AGRONOMICA', NULL, false, 'red', 'Portugal', 'approved'),
  ('AGUA SANTA', NULL, false, 'red', 'Portugal', 'approved'),
  ('AHMEUR BOU AHMEUR', NULL, false, 'rosé', 'Portugal', 'approved'),
  ('AIDANI ASPRO', NULL, false, 'white', 'Greece', 'approved'),
  ('AIDANI MAVRO', NULL, false, 'red', 'Greece', 'approved'),
  ('AIREN', NULL, false, 'white', 'Spain', 'approved'),
  ('ALARIJE', ARRAY['MALVASíA RIOJANA', 'ROJAL', 'ARIS', 'SUBIRAT PARENT'], false, 'white', 'Spain', 'approved'),
  ('ALB AROMAT', NULL, false, 'white', 'Romania', 'approved'),
  ('ALBALONGA', NULL, false, 'white', 'Germany', 'approved'),
  ('ALBANA BIANCA', NULL, false, 'white', 'Italy', 'approved'),
  ('ALBANELLO', NULL, false, 'white', 'Italy', 'approved'),
  ('ALBARANZEULI BIANCO', NULL, false, 'white', 'Italy', 'approved'),
  ('ALBARIN BLANCO', ARRAY['RAPOSO'], false, 'white', 'Spain', 'approved'),
  ('ALBAROLA', NULL, false, 'white', 'Italy', 'approved'),
  ('ALBAROSSA', NULL, false, 'red', 'Italy', 'approved'),
  ('ALBILLO MAYOR', ARRAY['TURRUNTéS'], false, 'white', 'Spain', 'approved'),
  ('ALBILLO REAL', NULL, false, 'white', 'Spain', 'approved'),
  ('ALCANON', NULL, false, 'white', 'Spain', 'approved'),
  ('ALEATICO', NULL, false, 'red', 'France', 'approved'),
  ('ALEGRILLO NEGRO', NULL, false, 'red', 'Spain', 'approved'),
  ('ALFROCHEIRO', ARRAY['BABOSO NEGRO'], false, 'red', 'Spain', 'approved'),
  ('ALICANTE HENRI BOUSCHET', NULL, false, 'red', 'Portugal', 'approved'),
  ('ALIGOTE', NULL, false, 'white', 'Czech Republic', 'approved'),
  ('ALIONZA', NULL, false, 'white', 'Italy', 'approved'),
  ('ALLEGRO', NULL, false, 'red', 'Germany', 'approved'),
  ('ALMAFRA', NULL, false, 'white', 'Portugal', 'approved'),
  ('ALPHONSE LAVALLEE', NULL, false, 'red', 'France', 'approved'),
  ('ALTESSE', NULL, false, 'white', 'France', 'approved'),
  ('ALUTUS', NULL, false, 'red', 'Romania', 'approved'),
  ('ALVADURAO', NULL, false, 'white', 'Portugal', 'approved'),
  ('ALVAR BRANCO', NULL, false, 'white', 'Portugal', 'approved'),
  ('ALVAR ROXO', NULL, false, 'red', 'Portugal', 'approved'),
  ('ALVAREGA', NULL, false, 'white', 'France', 'approved'),
  ('ALVARELHAO', NULL, false, 'red', 'Spain', 'approved'),
  ('ALVARELHAO CEITAO', NULL, false, 'red', 'Portugal', 'approved'),
  ('ALVARINHO', NULL, false, 'white', 'Spain', 'approved'),
  ('AMARAL', NULL, false, 'red', 'Portugal', 'approved'),
  ('AMFIONI', NULL, false, 'red', 'Greece', 'approved'),
  ('AMURG', NULL, false, 'red', 'Romania', 'approved'),
  ('ANCELLOTTA', ARRAY['????????'], false, 'red', 'Bulgaria', 'approved'),
  ('ANDRE', NULL, false, 'red', 'Czech Republic', 'approved'),
  ('ANSONICA', ARRAY['INZOLIA', 'INSOLIA'], false, 'white', 'Italy', 'approved'),
  ('ANTAO VAZ', NULL, false, 'white', 'Portugal', 'approved'),
  ('ARAIGNAN', ARRAY['ARAIGNAN B'], false, 'white', 'France', 'approved'),
  ('ARAKLINOS', NULL, false, 'red', 'Greece', 'approved'),
  ('ARAMON BLANC', NULL, false, 'white', 'France', 'approved'),
  ('ARAMON GRIS', NULL, false, 'white', 'France', 'approved'),
  ('ARAMON NOIR', NULL, false, 'red', 'Portugal', 'approved'),
  ('ARANEL', NULL, false, 'white', 'France', 'approved'),
  ('ARBANE', NULL, false, 'red', 'France', 'approved'),
  ('ARBOIS BLANC', NULL, false, 'white', 'France', 'approved'),
  ('ARCAS', NULL, false, 'red', 'Romania', 'approved'),
  ('ARETI', NULL, false, 'white', 'Greece', 'approved'),
  ('ARGESSIS', NULL, true, 'red', 'Romania', 'approved'),
  ('ARIANA', NULL, false, 'red', 'Czech Republic', 'approved'),
  ('ARINARNOA', NULL, false, 'red', 'France', 'approved'),
  ('ARINTHO', NULL, false, 'white', 'Greece', 'approved'),
  ('ARINTO', ARRAY['PEDERNã'], false, 'white', 'Portugal', 'approved'),
  ('ARINTO DO INTERIOR', NULL, false, 'white', 'Portugal', 'approved'),
  ('ARINTO ROXO', NULL, false, 'red', 'Portugal', 'approved'),
  ('ARNEIS', NULL, false, 'white', 'Italy', 'approved'),
  ('ARNSBURGER', NULL, false, 'white', 'Germany', 'approved'),
  ('AROMAT DE IASI', NULL, false, 'white', 'Romania', 'approved'),
  ('ARRILOBA', NULL, false, 'white', 'France', 'approved'),
  ('ARROUYA', NULL, false, 'red', 'France', 'approved'),
  ('ARRUFIAC', ARRAY['ARRUFIAT B'], false, 'white', 'France', 'approved'),
  ('ARVESINIADU', NULL, false, 'white', 'Italy', 'approved'),
  ('ARVINE PETITE', NULL, false, 'white', 'Italy', 'approved'),
  ('ASPIRAN BLANC', ARRAY['ASPIRAN BLANC B'], false, 'white', 'France', 'approved'),
  ('ASPIRAN GRIS', ARRAY['ASPIRAN GRIS G'], false, 'white', 'France', 'approved'),
  ('ASPIRAN NOIR', ARRAY['ASPIRAN N'], false, 'red', 'France', 'approved'),
  ('ASPROMANDILARIA', NULL, false, 'white', 'Greece', 'approved'),
  ('ASPROUDA PATRON', ARRAY['SANTAMERIANA'], false, 'white', 'Greece', 'approved'),
  ('ASPROUDA SANTORINES', NULL, false, 'white', 'Greece', 'approved'),
  ('ASPROUDA SERRON', NULL, false, 'white', 'Greece', 'approved'),
  ('ASPROUDES', NULL, false, 'white', 'Greece', 'approved'),
  ('ASSYRTIKO', NULL, false, 'white', 'Bulgaria', 'approved'),
  ('ASTRA', NULL, false, 'white', 'Romania', 'approved'),
  ('ATHIRI (THRAPSATHIRI)', NULL, false, 'white', 'Greece', 'approved'),
  ('ATHIRI LEFKO (KOTINIS)', NULL, false, 'white', 'Greece', 'approved'),
  ('ATHIRI MAVRO', ARRAY['MAVRATHIRO'], false, 'red', 'Greece', 'approved'),
  ('AUBIN BLANC', NULL, false, 'white', 'France', 'approved'),
  ('AUBIN VERT', NULL, false, 'white', 'France', 'approved'),
  ('AUBUN', ARRAY['MURESCOLA N'], false, 'red', 'France', 'approved'),
  ('AURELIUS', NULL, false, 'white', 'Czech Republic', 'approved'),
  ('AUXERROIS', NULL, false, 'white', 'Czech Republic', 'approved'),
  ('AVANA', NULL, false, 'red', 'Italy', 'approved'),
  ('AVARENGO', NULL, false, 'red', 'Italy', 'approved'),
  ('AVESSO', NULL, false, 'white', 'Portugal', 'approved'),
  ('AVGOUSTIATIS', NULL, false, 'red', 'Greece', 'approved'),
  ('AZAL BRANCO', NULL, false, 'white', 'Portugal', 'approved'),
  ('BABEASCA GRIS', NULL, false, 'white', 'Romania', 'approved'),
  ('BABEASCA NEAGRA', NULL, false, 'red', 'Romania', 'approved'),
  ('BACCHUS WEISS', NULL, false, 'white', 'Czech Republic', 'approved'),
  ('BACHET NOIR', NULL, false, 'red', 'France', 'approved'),
  ('BACO BLANC', ARRAY['BACO 22 A'], true, 'white', 'France', 'approved'),
  ('BAGA', NULL, false, 'red', 'Portugal', 'approved'),
  ('BALADA', NULL, false, 'red', 'Romania', 'approved'),
  ('BARATUCIAT', NULL, false, 'white', 'Italy', 'approved'),
  ('BARBAROUX', NULL, false, 'rosé', 'France', 'approved'),
  ('BARBERA BIANCA', NULL, false, 'white', 'Italy', 'approved'),
  ('BARBERA NERA', NULL, false, 'red', 'Greece', 'approved'),
  ('BARBERA SARDA', NULL, false, 'red', 'Italy', 'approved'),
  ('BARCA', NULL, false, 'red', 'Portugal', 'approved'),
  ('BARCELO', NULL, false, 'white', 'Portugal', 'approved'),
  ('BARON', NULL, false, 'white', 'Germany', 'approved'),
  ('BAROQUE', NULL, false, 'white', 'France', 'approved'),
  ('BARRETO', NULL, false, 'red', 'Portugal', 'approved'),
  ('BARSAGLINA', ARRAY['MASSARETTA'], false, 'red', 'Italy', 'approved'),
  ('BASTARDO BRANCO', ARRAY['BABOSO BLANCO'], false, 'white', 'Spain', 'approved'),
  ('BASTARDO ROXO', NULL, false, 'red', 'Portugal', 'approved'),
  ('BATIKI', NULL, false, 'white', 'Greece', 'approved'),
  ('BATOCA', NULL, false, 'white', 'Portugal', 'approved'),
  ('BEBA', NULL, false, 'white', 'Portugal', 'approved'),
  ('BECLAN PETIT', ARRAY['PETIT BéCLAN N'], false, 'red', 'France', 'approved'),
  ('BEKARI', NULL, false, 'red', 'Greece', 'approved'),
  ('BELLONE', ARRAY['CACCHIONE'], false, 'white', 'Italy', 'approved'),
  ('BEQUIGNOL NOIR', NULL, false, 'red', 'France', 'approved'),
  ('BESGANO NERO', NULL, false, 'red', 'Italy', 'approved'),
  ('BIANCA', NULL, true, 'white', 'Hungary', 'approved'),
  ('BIANCHETTA TREVIGIANA', NULL, false, 'white', 'Italy', 'approved'),
  ('BIANCO D''ALESSANO', NULL, false, 'white', 'Italy', 'approved'),
  ('BIANCOLELLA', ARRAY['JANCULILLO', 'JANCULELLA'], false, 'white', 'Italy', 'approved'),
  ('BIANCONE', NULL, false, 'white', 'Italy', 'approved'),
  ('BIANCU GENTILE', NULL, false, 'white', 'France', 'approved'),
  ('BIAYADI', ARRAY['???????? ?????'], false, 'red', 'Bulgaria', 'approved'),
  ('BIBORFRANKOS', NULL, false, 'red', 'Hungary', 'approved'),
  ('BIBORKADARKA', NULL, false, 'red', 'Hungary', 'approved'),
  ('BICAL', NULL, false, 'white', 'Portugal', 'approved'),
  ('BIRSTALER MUSKAT', NULL, true, 'white', 'Germany', 'approved'),
  ('BLANC DAME', NULL, false, 'white', 'France', 'approved'),
  ('BLASIUS', NULL, false, 'white', 'Romania', 'approved'),
  ('BLAUBURGER', NULL, false, 'other', 'Austria', 'approved'),
  ('BLAUFRAENKISCH', ARRAY['BLAUFRäNKISCH', 'LEMBERGER', 'LIMBERGER'], false, 'red', 'Germany', 'approved'),
  ('BOAL BARREIRO', NULL, false, 'white', 'Portugal', 'approved'),
  ('BOAL BRANCO', NULL, false, 'white', 'Portugal', 'approved'),
  ('BOAL ESPINHO', NULL, false, 'white', 'Portugal', 'approved'),
  ('BOAL VENCEDOR', NULL, false, 'white', 'Portugal', 'approved'),
  ('BOBAL', NULL, false, 'red', 'Spain', 'approved'),
  ('BOGHIALAMADES', NULL, false, 'red', 'Greece', 'approved'),
  ('BOLERO', NULL, true, 'white', 'Germany', 'approved'),
  ('BOMBINO BIANCO', ARRAY['OTTENESE', 'BOMBINO*', 'BONVINO*'], false, 'white', 'Italy', 'approved'),
  ('BOMBINO NERO', ARRAY['BOMBINO*', 'BONVINO*'], false, 'red', 'Italy', 'approved'),
  ('BONAMICO', NULL, false, 'red', 'Italy', 'approved'),
  ('BONARDA PIEMONTESE', ARRAY['UVA RARA (WRONG)'], false, 'red', 'Italy', 'approved'),
  ('BORRACAL', NULL, false, 'red', 'Portugal', 'approved'),
  ('BOSCHERA', NULL, false, 'white', 'Italy', 'approved'),
  ('BOSCO', NULL, false, 'white', 'Italy', 'approved'),
  ('BOUCHALES', NULL, false, 'red', 'France', 'approved'),
  ('BOUILLET', NULL, false, 'red', 'France', 'approved'),
  ('BOURBOULENC', NULL, false, 'white', 'Spain', 'approved'),
  ('BOUSCHET PETIT', NULL, false, 'red', 'Portugal', 'approved'),
  ('BOUVIER', NULL, false, 'white', 'Czech Republic', 'approved'),
  ('BRACCIOLA NERA', NULL, false, 'red', 'Italy', 'approved'),
  ('BRACHETTO', NULL, false, 'red', 'Italy', 'approved'),
  ('BRANCA DE ANADIA', NULL, false, 'white', 'Portugal', 'approved'),
  ('BRANCO DESCONHECIDO', NULL, false, 'white', 'Portugal', 'approved'),
  ('BRANCO ESCOLA', NULL, false, 'white', 'Portugal', 'approved'),
  ('BRANCO GOUVAES', NULL, false, 'white', 'Portugal', 'approved'),
  ('BRANCO GUIMARAES', NULL, false, 'white', 'Portugal', 'approved'),
  ('BRANCO SR. JOAO', NULL, false, 'white', 'Portugal', 'approved'),
  ('BRANDA', NULL, false, 'white', 'Portugal', 'approved'),
  ('BRANDAM', NULL, false, 'white', 'Portugal', 'approved'),
  ('BRANJO', NULL, false, 'red', 'Portugal', 'approved'),
  ('BRAQUET NOIR', ARRAY['BRAQUET N'], false, 'red', 'France', 'approved'),
  ('BRIC', NULL, false, 'red', 'Italy', 'approved'),
  ('BRONNER', NULL, false, 'white', 'Germany', 'approved'),
  ('BRUMARIU', NULL, false, 'white', 'Romania', 'approved'),
  ('BRUN ARGENTE', ARRAY['VACCARèSE N'], false, 'red', 'France', 'approved'),
  ('BRUN FOURCA', NULL, false, 'red', 'France', 'approved'),
  ('BRUNI  54', NULL, false, 'white', 'Italy', 'approved'),
  ('BUDAI ZOELD', NULL, false, 'white', 'Hungary', 'approved'),
  ('BUKET', NULL, false, 'other', 'Bulgaria', 'approved'),
  ('BUKETTREBE', NULL, false, 'white', 'France', 'approved'),
  ('BURGUND 63 MN', NULL, false, 'red', 'Romania', 'approved'),
  ('BUSSANELLO', NULL, false, 'white', 'Italy', 'approved'),
  ('CABERNET CANTOR', NULL, true, 'red', 'Germany', 'approved'),
  ('CABERNET CARBON', NULL, false, 'red', 'Germany', 'approved'),
  ('CABERNET CAROL', NULL, false, 'red', 'Germany', 'approved'),
  ('CABERNET CORTIS', NULL, false, 'red', 'Germany', 'approved'),
  ('CABERNET CUBIN', ARRAY['CUBIN'], false, 'red', 'Germany', 'approved'),
  ('CABERNET DORIO', ARRAY['DORIO'], false, 'red', 'Germany', 'approved'),
  ('CABERNET DORSA', ARRAY['DORSA'], false, 'red', 'Germany', 'approved'),
  ('CABERNET FRANC', NULL, false, 'red', 'Spain', 'approved'),
  ('CABERNET MITOS', ARRAY['MITOS'], false, 'red', 'Germany', 'approved'),
  ('CABERNET MORAVIA', NULL, false, 'red', 'Czech Republic', 'approved'),
  ('CABERNET SAUVIGNON', NULL, false, 'red', 'Spain', 'approved'),
  ('CABINDA', NULL, false, 'red', 'Portugal', 'approved'),
  ('CABRAL', NULL, false, 'red', 'Portugal', 'approved'),
  ('CADDIU', NULL, false, 'red', 'Italy', 'approved'),
  ('CAINO BLANCO', NULL, false, 'white', 'Portugal', 'approved'),
  ('CAINO LONGO 1', NULL, false, 'red', 'Spain', 'approved'),
  ('CALABRESE', ARRAY['NERO D''AVOLA'], false, 'red', 'Italy', 'approved'),
  ('CALADOC', NULL, false, 'red', 'Portugal', 'approved'),
  ('CALITOR NOIR', ARRAY['PéCOUI TOUAR N'], false, 'red', 'France', 'approved'),
  ('CALLET', NULL, false, 'red', 'Spain', 'approved'),
  ('CALORIA', NULL, false, 'red', 'Italy', 'approved'),
  ('CALRAO', NULL, false, 'red', 'Portugal', 'approved'),
  ('CAMARALET FEMELLE', NULL, false, 'white', 'France', 'approved'),
  ('CAMARATE TINTO', NULL, false, 'red', 'Portugal', 'approved'),
  ('CAMPANARIO', NULL, false, 'red', 'Portugal', 'approved'),
  ('CANAIOLO NERO', NULL, false, 'red', 'Italy', 'approved'),
  ('CANAIOLO ROSA', NULL, false, 'rosé', 'Italy', 'approved'),
  ('CANINA NERA', NULL, false, 'red', 'Italy', 'approved'),
  ('CANTARO', NULL, false, 'white', 'Germany', 'approved'),
  ('CAPOLONGO', NULL, false, 'white', 'Italy', 'approved'),
  ('CARACOL', NULL, false, 'white', 'Portugal', 'approved'),
  ('CARDINAL', NULL, false, 'red', 'France', 'approved'),
  ('CARIGNAN BLANC', NULL, false, 'white', 'France', 'approved'),
  ('CARIGNAN NOIR', NULL, false, 'red', 'Portugal', 'approved'),
  ('CARMENERE', NULL, false, 'red', 'France', 'approved'),
  ('CARRASQUIN', NULL, false, 'red', 'Spain', 'approved'),
  ('CARREGA BRANCO', NULL, false, 'white', 'Portugal', 'approved'),
  ('CARREGA BURROS', NULL, false, 'red', 'Portugal', 'approved'),
  ('CARREGA TINTO', NULL, false, 'red', 'Portugal', 'approved'),
  ('CARRICANTE', NULL, false, 'white', 'Italy', 'approved'),
  ('CASAVECCHIA', NULL, false, 'red', 'Italy', 'approved'),
  ('CASCAL', NULL, false, 'white', 'Portugal', 'approved'),
  ('CASCULHO', NULL, false, 'red', 'Portugal', 'approved'),
  ('CASTALIA', NULL, false, 'white', 'Portugal', 'approved'),
  ('CASTANAL', NULL, false, 'red', 'Spain', 'approved'),
  ('CASTELA', NULL, false, 'red', 'Portugal', 'approved'),
  ('CASTELAO BRANCO', NULL, false, 'white', 'Portugal', 'approved'),
  ('CASTELOA', NULL, false, 'red', 'Portugal', 'approved'),
  ('CASTETS', NULL, false, 'red', 'France', 'approved'),
  ('CATANESE NERO', NULL, false, 'red', 'Italy', 'approved'),
  ('CATARRATTO BIANCO COMUNE', ARRAY['CATARRATTO*'], false, 'white', 'Italy', 'approved'),
  ('CAYETANA BLANCA', ARRAY['BALADí', 'BALADí VERDEJO', 'CALAGRAñO', 'JAéN BLANCO', 'ROBAL'], false, 'white', 'Spain', 'approved'),
  ('CELLERINA', NULL, false, 'red', 'Italy', 'approved'),
  ('CELTICA', NULL, false, 'white', 'Italy', 'approved'),
  ('CENTESIMINO', NULL, false, 'red', 'Italy', 'approved'),
  ('CERCEAL BRANCO', NULL, false, 'white', 'Portugal', 'approved'),
  ('CERCIAL', NULL, false, 'white', 'Portugal', 'approved'),
  ('CESANESE COMUNE', ARRAY['CESANESE*'], false, 'red', 'Italy', 'approved'),
  ('CESANESE D''AFFILE', NULL, false, 'red', 'Italy', 'approved'),
  ('CESAR', NULL, false, 'red', 'France', 'approved'),
  ('CHAMBOURCIN', ARRAY['26205 JOANNèS SEYVE'], true, 'red', 'France', 'approved'),
  ('CHARDONNAY BLANC', ARRAY['???????'], false, 'white', 'Bulgaria', 'approved'),
  ('CHARDONNAY ROSE', ARRAY['CHARDONNAY'], false, 'rosé', NULL, 'approved'),
  ('CHASAN', NULL, false, 'white', 'Spain', 'approved'),
  ('CHASSELAS BLANC', ARRAY['FEHéR CHASSELAS'], false, 'white', 'Hungary', 'approved'),
  ('CHASSELAS CIOUTAT', NULL, false, 'white', 'Portugal', 'approved'),
  ('CHASSELAS ROSE', NULL, false, 'rosé', 'France', 'approved'),
  ('CHASSELAS SABOR', NULL, false, 'white', 'Portugal', 'approved'),
  ('CHATUS', NULL, false, 'red', 'France', 'approved'),
  ('CHENANSON', NULL, false, 'red', 'France', 'approved'),
  ('CHENIN BLANC', NULL, false, 'white', 'Spain', 'approved'),
  ('CHERNOMORSKI BRILIANT', ARRAY['??????????? ???????'], false, 'white', 'Bulgaria', 'approved'),
  ('CHERNOMORSKI ELEKSIR', ARRAY['??????????? E??????'], false, 'white', 'Bulgaria', 'approved'),
  ('CHIDIRIOTIKO', ARRAY['KALLONIATIKO'], false, 'red', 'Greece', 'approved'),
  ('CHIOTIKO KRASSERO', NULL, false, 'red', 'Greece', 'approved'),
  ('CHLORES', NULL, false, 'white', 'Greece', 'approved'),
  ('CHONDROMAVRO', NULL, false, 'red', 'Greece', 'approved'),
  ('CIANORIE', NULL, false, 'red', 'Italy', 'approved'),
  ('CIDADELHE', NULL, false, 'red', 'Portugal', 'approved'),
  ('CIDREIRO', NULL, false, 'red', 'Portugal', 'approved'),
  ('CILIEGIOLO', ARRAY['MORETTONE'], false, 'red', 'Italy', 'approved'),
  ('CINSAUT', NULL, false, 'red', 'Portugal', 'approved'),
  ('CIVIDIN BIANCO', NULL, false, 'white', 'Italy', 'approved'),
  ('CLAIRETTE BLANCHE', NULL, false, 'white', 'France', 'approved'),
  ('CLAIRETTE ROSE', NULL, false, 'rosé', 'France', 'approved'),
  ('CLARIN', NULL, false, 'white', 'France', 'approved'),
  ('CLAVERIE', NULL, false, 'white', 'France', 'approved'),
  ('COCOCCIOLA', NULL, false, 'white', 'Italy', 'approved'),
  ('CODANA', NULL, false, 'red', 'Romania', 'approved'),
  ('CODEGA DO LARINHO', NULL, false, 'white', 'Portugal', 'approved'),
  ('COLOBEL', ARRAY['8357 SEIBEL'], true, 'red', 'France', 'approved'),
  ('COLOMBARD', NULL, false, 'white', 'Spain', 'approved'),
  ('COLOMBAUD', ARRAY['COLOMBAUD B'], false, 'white', 'France', 'approved'),
  ('COLORAILLO', NULL, false, 'white', 'Spain', 'approved'),
  ('COLUMNA', NULL, false, 'white', 'Romania', 'approved'),
  ('COMPLEXA', NULL, false, 'red', 'Portugal', 'approved'),
  ('CONCIEIRA', NULL, false, 'red', 'Portugal', 'approved'),
  ('CORACAO DE GALO', NULL, false, 'red', 'Portugal', 'approved'),
  ('CORBEAU', ARRAY['DOUCE NOIRE N'], false, 'red', 'France', 'approved'),
  ('CORDENOSSA', NULL, false, 'red', 'Italy', 'approved'),
  ('CORNALIN D''AOSTE', NULL, false, 'red', 'Italy', 'approved'),
  ('CORNAREA', NULL, false, 'red', 'Italy', 'approved'),
  ('CORNICHON BLANC', NULL, false, 'white', 'Portugal', 'approved'),
  ('CORNIFESTO', NULL, false, 'red', 'Portugal', 'approved'),
  ('CORREDERA', NULL, false, 'white', 'Spain', 'approved'),
  ('CORTESE', ARRAY['BIANCA FERNANDA *'], false, 'white', 'Italy', 'approved'),
  ('CORVAL', NULL, false, 'white', 'Portugal', 'approved'),
  ('CORVINA VERONESE', ARRAY['CRUINA'], false, 'red', 'Italy', 'approved'),
  ('CORVINONE VERONESE', NULL, false, 'red', 'Italy', 'approved'),
  ('COT', ARRAY['MALBEC N'], false, 'red', 'France', 'approved'),
  ('COUDERC NOIR', ARRAY['7120 COUDERC'], true, 'red', 'France', 'approved'),
  ('COUNOISE', NULL, false, 'red', 'France', 'approved'),
  ('COURBU BLANC', ARRAY['GROS COURBU B'], false, 'white', 'France', 'approved'),
  ('COURBU NOIR', NULL, false, 'red', 'France', 'approved'),
  ('COURBU PETIT', NULL, false, 'white', 'Spain', 'approved'),
  ('COVE', NULL, false, 'white', 'Italy', 'approved'),
  ('CRIMPOSIE SELECTIONATA', NULL, false, 'white', 'Romania', 'approved'),
  ('CRISTINA', NULL, false, 'red', 'Romania', 'approved'),
  ('CROATINA', ARRAY['BONARDA *'], false, 'red', 'Italy', 'approved'),
  ('CROUCHEN', ARRAY['CRUCHEN B'], false, 'white', 'France', 'approved'),
  ('CROVASSA', NULL, false, 'red', 'Italy', 'approved'),
  ('CSABA GYOENGYE', NULL, false, 'white', 'Hungary', 'approved'),
  ('CSERSZEGI FUESZERES', NULL, false, 'white', 'Hungary', 'approved'),
  ('CSOMORIKA', NULL, false, 'white', 'Hungary', 'approved'),
  ('CUDIVERTA', NULL, false, 'white', 'France', 'approved'),
  ('CUMDEO BLANC', NULL, false, 'white', 'Spain', 'approved'),
  ('CUMDEO ROUGE', NULL, false, 'red', 'Spain', 'approved'),
  ('DAKAPO', NULL, false, 'red', 'Germany', 'approved'),
  ('DANLAS', NULL, false, 'white', 'Portugal', 'approved'),
  ('DAPHNIA', ARRAY['DAFNIA'], false, 'white', 'Greece', 'approved'),
  ('DEBINA', NULL, false, 'white', 'Greece', 'approved'),
  ('DECKROT', NULL, false, 'red', 'Germany', 'approved'),
  ('DEDO DE DAMA', NULL, false, 'white', 'Portugal', 'approved'),
  ('DELICIOSA', NULL, false, 'red', 'Portugal', 'approved'),
  ('DERECHERO', NULL, false, 'red', 'Spain', 'approved'),
  ('DERMATAS', NULL, false, 'white', 'Greece', 'approved'),
  ('DEVIN', NULL, false, 'white', 'Czech Republic', 'approved'),
  ('DIMYAT', ARRAY['?????'], false, 'white', 'Bulgaria', 'approved'),
  ('DINDARELLA', NULL, false, 'red', 'Italy', 'approved'),
  ('DIOLINOIR', NULL, false, 'red', 'Italy', 'approved'),
  ('DOCAL TINTO', NULL, false, 'red', 'Portugal', 'approved'),
  ('DOCE', NULL, false, 'red', 'Portugal', 'approved'),
  ('DOLCETTO', ARRAY['ORMEASCO'], false, 'red', 'Italy', 'approved'),
  ('DOLCIAME', NULL, false, 'white', 'Italy', 'approved'),
  ('DOMINA', NULL, false, 'red', 'Germany', 'approved'),
  ('DONA JOAQUINA', NULL, false, 'white', 'Portugal', 'approved'),
  ('DONARIS', NULL, false, 'white', 'Romania', 'approved'),
  ('DONZELINHO BRANCO', NULL, false, 'white', 'Portugal', 'approved'),
  ('DONZELINHO ROXO', NULL, false, 'red', 'Portugal', 'approved'),
  ('DONZELINHO TINTO', NULL, false, 'red', 'Portugal', 'approved'),
  ('DORADILLA', NULL, false, 'white', 'Spain', 'approved'),
  ('DORNFELDER', NULL, false, 'red', 'Czech Republic', 'approved'),
  ('DOUX D''HENRI', NULL, false, 'red', 'Italy', 'approved'),
  ('DROUJBA', ARRAY['??????'], true, 'white', 'Bulgaria', 'approved'),
  ('DUNA GYOENGYE', NULL, false, 'red', 'Hungary', 'approved'),
  ('DUNAJ', NULL, false, 'red', 'Czech Republic', 'approved'),
  ('DUNKELFELDER', NULL, false, 'red', 'Germany', 'approved'),
  ('DURAS', NULL, false, 'red', 'France', 'approved'),
  ('DURASA', NULL, false, 'red', 'Italy', 'approved'),
  ('DURELLA', ARRAY['DURELLO'], false, 'white', 'Italy', 'approved'),
  ('DURIF', NULL, false, 'red', 'France', 'approved'),
  ('EGIODOLA', NULL, false, 'red', 'Bulgaria', 'approved'),
  ('EHRENBREITSTEINER', NULL, false, 'white', 'Germany', 'approved'),
  ('EHRENFELSER', NULL, false, 'white', 'Germany', 'approved'),
  ('EKIGAINA', NULL, false, 'red', 'France', 'approved'),
  ('ELBLING BLAU', ARRAY['WILLBACHER'], false, 'red', NULL, 'approved'),
  ('ELBLING ROT', ARRAY['ELBLING', 'ELBLING ROUGE'], false, 'rosé', 'Germany', 'approved'),
  ('ELBLING WEISS', NULL, false, 'white', 'France', 'approved'),
  ('ENCRUZADO', NULL, false, 'white', 'Portugal', 'approved'),
  ('ENGOMADA', NULL, false, 'red', 'Portugal', 'approved'),
  ('ERBALUCE BIANCA', NULL, false, 'white', 'Italy', 'approved'),
  ('ERBAMAT', NULL, false, 'white', 'Italy', 'approved'),
  ('ERVI', NULL, false, 'red', 'Italy', 'approved'),
  ('ESGANACAO PRETO', NULL, false, 'red', 'Portugal', 'approved'),
  ('ESGANINHO', NULL, false, 'white', 'Portugal', 'approved'),
  ('ESGANOSO', NULL, false, 'white', 'Portugal', 'approved'),
  ('ESTREITO MACIO', NULL, false, 'white', 'Portugal', 'approved'),
  ('ETRAIRE DE LA DUI', NULL, false, 'red', 'France', 'approved'),
  ('EVMOLPIYA', ARRAY['????????'], false, 'red', 'Bulgaria', 'approved'),
  ('EZERFUERTUE', NULL, false, 'white', 'Hungary', 'approved'),
  ('EZERJO', NULL, false, 'white', 'Hungary', 'approved'),
  ('FABERREBE', NULL, false, 'white', 'Germany', 'approved'),
  ('FALANGHINA  FLEGREA', NULL, false, 'white', 'Italy', 'approved'),
  ('FELICIA', NULL, false, 'white', 'Germany', 'approved'),
  ('FENILE', NULL, false, 'white', 'Italy', 'approved'),
  ('FEPIRO', NULL, false, 'red', 'Portugal', 'approved'),
  ('FER', ARRAY['BRAUCOL N', 'FER SERVADOU N', 'MANSOIS N', 'PINENC N'], false, 'red', 'France', 'approved'),
  ('FERNAO PIRES', ARRAY['MARIA GOMES'], false, 'white', 'Portugal', 'approved'),
  ('FERNAO PIRES ROSADO', NULL, false, 'red', 'Portugal', 'approved'),
  ('FERTILIA', NULL, false, 'red', 'Italy', 'approved'),
  ('FETEASCA ALBA', NULL, false, 'white', 'Romania', 'approved'),
  ('FETEASCA NEAGRA', NULL, false, 'red', 'Romania', 'approved'),
  ('FETEASCA REGALA', NULL, false, 'white', 'Romania', 'approved'),
  ('FEUNATE', NULL, false, 'red', 'France', 'approved'),
  ('FIANO', NULL, false, 'other', 'Bulgaria', 'approved'),
  ('FILERI ATTIKIS', NULL, false, 'rosé', 'Greece', 'approved'),
  ('FLASKASSYRTIKO', NULL, false, 'white', 'Greece', 'approved'),
  ('FLAVIS', NULL, false, 'white', 'Italy', 'approved'),
  ('FLEURIEN NOIR', NULL, false, 'red', 'France', 'approved'),
  ('FLORENTAL', ARRAY['7705 BURDIN'], true, 'red', 'France', 'approved'),
  ('FOGARINA', NULL, false, 'red', 'Italy', 'approved'),
  ('FOGLIA TONDA', NULL, false, 'red', 'Italy', 'approved'),
  ('FOGONEU', NULL, false, 'red', 'Spain', 'approved'),
  ('FOKIANO', NULL, false, 'red', 'Greece', 'approved'),
  ('FOLGASAO', NULL, false, 'white', 'Portugal', 'approved'),
  ('FOLGASAO ROXO', NULL, false, 'red', 'Portugal', 'approved'),
  ('FOLHA DE FIGUEIRA', NULL, false, 'white', 'Portugal', 'approved'),
  ('FOLIGNAN', NULL, false, 'white', 'France', 'approved'),
  ('FOLLE BLANCHE', ARRAY['MATZA ZURI'], false, 'white', 'Spain', 'approved'),
  ('FONTANARA', NULL, false, 'white', 'Germany', 'approved'),
  ('FONTE CAL', NULL, false, 'white', 'Portugal', 'approved'),
  ('FORASTERA', ARRAY['FORESTIERA', 'FURASTIERA'], false, 'white', 'Italy', 'approved'),
  ('FORCALLAT TINTA', NULL, false, 'red', 'Spain', 'approved'),
  ('FORSELLINA', NULL, false, 'red', 'Italy', 'approved'),
  ('FORTANA NERA', ARRAY['UVA D''ORO'], false, 'red', 'Italy', 'approved'),
  ('FRANC NOIR DE LA HAUTE SAONE', NULL, false, 'red', 'France', 'approved'),
  ('FRANCUSE', NULL, false, 'white', 'Romania', 'approved'),
  ('FRAPPATO DI VITTORIA', ARRAY['FRAPPATO D'' ITALIA'], false, 'red', 'Italy', 'approved'),
  ('FREISA', NULL, false, 'red', 'Italy', 'approved'),
  ('FREISAMER', NULL, false, 'white', 'Germany', 'approved'),
  ('FRIULANO', ARRAY['FRIULANO*'], false, 'white', 'Italy', 'approved'),
  ('FUBIANO', NULL, false, 'white', 'Italy', 'approved'),
  ('FUELLA NERA', ARRAY['FOLLE NOIRE DE NICE N'], false, 'red', 'France', 'approved'),
  ('FUMIN', NULL, false, 'red', 'Italy', 'approved'),
  ('FURMINT', NULL, false, 'white', 'Hungary', 'approved'),
  ('GAGLIOPPO', ARRAY['MAGLIOPPO', 'MAGLIOCCO'], false, 'red', 'Italy', 'approved'),
  ('GAIDOURIA', NULL, false, 'white', 'Greece', 'approved'),
  ('GALEGO DOURADO', NULL, false, 'white', 'Portugal', 'approved'),
  ('GALEGO DOURADO TINTO', NULL, false, 'red', 'Portugal', 'approved'),
  ('GALEGO ROSADO', NULL, false, 'red', 'Portugal', 'approved'),
  ('GAMARET', NULL, false, 'red', 'France', 'approved'),
  ('GAMAY NOIR', NULL, false, 'red', 'Portugal', 'approved'),
  ('GAMAY TEINTURIER DE BOUZE', NULL, false, 'red', 'Bulgaria', 'approved'),
  ('GAMAY TEINTURIER DE CHAUDENAY', NULL, false, 'red', 'France', 'approved'),
  ('GAMAY TEINTURIER FREAUX', NULL, false, 'red', 'Bulgaria', 'approved'),
  ('GAMBA ROSSA', ARRAY['IMPERATRICE DALLA GAMBA ROSSA'], false, 'red', 'Italy', 'approved'),
  ('GANSON', NULL, false, 'red', 'France', 'approved'),
  ('GARANOIR', NULL, false, 'red', 'Italy', 'approved'),
  ('GARGANEGA', ARRAY['GARGANEGO *'], false, 'white', 'Italy', 'approved'),
  ('GARNACHA BLANCA', ARRAY['LLADONER BLANCO'], false, 'white', 'Spain', 'approved'),
  ('GARNACHA PELUDA', NULL, false, 'red', 'Spain', 'approved'),
  ('GARNACHA ROJA', ARRAY['GARNACHA GRIS'], false, 'red', 'Spain', 'approved'),
  ('GARNACHA TINTA', ARRAY['GARNACHA TINTA', 'GRANACCIA', 'GRENACHE', 'GUARNACCIA', 'CANNONAO', 'GAMAY*', 'TAI*'], false, 'red', 'Italy', 'approved'),
  ('GARONNET', ARRAY['18283 SEYVE-VILLARD'], true, 'red', 'France', 'approved'),
  ('GARRIDO FINO', NULL, false, 'white', 'Spain', 'approved'),
  ('GASCON', NULL, false, 'red', 'France', 'approved'),
  ('GELBHOELZER BLAU', ARRAY['GELBHöLZER'], false, 'red', NULL, 'approved'),
  ('GENEROSA', NULL, false, 'white', 'Portugal', 'approved'),
  ('GENOVESE', NULL, false, 'white', 'France', 'approved'),
  ('GERGANA', ARRAY['???????'], false, 'white', 'Bulgaria', 'approved'),
  ('GESZTUS', NULL, false, 'white', 'Hungary', 'approved'),
  ('GEWUERZTRAMINER', NULL, false, 'rosé', 'Greece', 'approved'),
  ('GINESTRA', NULL, false, 'white', 'Italy', 'approved'),
  ('GIRO BLANCO', NULL, false, 'white', 'Spain', 'approved'),
  ('GIRO NERO', NULL, false, 'red', 'Italy', 'approved'),
  ('GIRO ROS', NULL, false, 'red', 'Spain', 'approved'),
  ('GLERA', ARRAY['SERPRINO *', 'GLERA'], false, 'white', 'Italy', 'approved'),
  ('GLYKADA ASPRI', NULL, false, 'white', 'Greece', 'approved'),
  ('GLYKERITHRA', NULL, false, 'white', 'Greece', 'approved'),
  ('GLYKOPATI', NULL, false, 'red', 'Greece', 'approved'),
  ('GOECSEJI ZAMATOS', NULL, true, 'white', 'Hungary', 'approved'),
  ('GOLDBURGER', NULL, false, 'other', 'Austria', 'approved'),
  ('GOLDRIESLING', NULL, false, 'white', 'Germany', 'approved'),
  ('GOLDTRAMINER', NULL, false, 'white', 'Italy', 'approved'),
  ('GOLIA', NULL, true, 'white', 'Romania', 'approved'),
  ('GONCALO PIRES', NULL, false, 'red', 'Portugal', 'approved'),
  ('GORGOLLASA', NULL, false, 'red', 'Spain', 'approved'),
  ('GOSEN', NULL, false, 'red', 'Italy', 'approved'),
  ('GOUGET', NULL, false, 'red', 'France', 'approved'),
  ('GOUSTOLIDI', ARRAY['AVGOUSTOLIDI', 'VOSTILIDAS'], false, 'white', 'Greece', 'approved'),
  ('GOUVEIO', NULL, false, 'white', 'Portugal', 'approved'),
  ('GOUVEIO ESTIMADO', NULL, false, 'white', 'Portugal', 'approved'),
  ('GOUVEIO PRETO', NULL, false, 'red', 'Portugal', 'approved'),
  ('GOUVEIO REAL', NULL, false, 'white', 'Portugal', 'approved'),
  ('GOUVEIO ROXO', NULL, false, 'red', 'Portugal', 'approved'),
  ('GRACIANO', ARRAY['CAGNIULARI'], false, 'red', 'Italy', 'approved'),
  ('GRAISSE', NULL, false, 'white', 'France', 'approved'),
  ('GRAMON', NULL, false, 'red', 'France', 'approved'),
  ('GRAND NOIR', NULL, false, 'red', 'Portugal', 'approved'),
  ('GRANGEAL', NULL, false, 'red', 'Portugal', 'approved'),
  ('GRANHO', NULL, false, 'white', 'Portugal', 'approved'),
  ('GRAPARIOL', NULL, false, 'white', 'Italy', 'approved'),
  ('GRASA DE COTNARI', NULL, false, 'white', 'Romania', 'approved'),
  ('GRASSEN', ARRAY['GRASSENC N'], false, 'red', 'France', 'approved'),
  ('GRECHETTO BIANCO', ARRAY['GRECHETTO GENTILE'], false, 'white', 'Italy', 'approved'),
  ('GRECHETTO ROSSO', NULL, false, 'red', 'Italy', 'approved'),
  ('GRECO BIANCO DI TUFO', ARRAY['GRECO DI TUFO'], false, 'white', 'Greece', 'approved'),
  ('GRECO NERO', ARRAY['GRECO *', 'MAGLIOCCONE', 'GREGU NIEDDU'], false, 'red', 'Italy', 'approved'),
  ('GRIGNOLINO', NULL, false, 'red', 'Italy', 'approved'),
  ('GRILLO', NULL, false, 'white', 'Italy', 'approved'),
  ('GRINGET', NULL, false, 'white', 'France', 'approved'),
  ('GROLLEAU GRIS', NULL, false, 'white', 'France', 'approved'),
  ('GROLLEAU NOIR', NULL, false, 'red', 'France', 'approved'),
  ('GROPPELLO DI MOCASINA', NULL, false, 'red', 'Italy', 'approved'),
  ('GROPPELLO GENTILE', ARRAY['GROPPELLO *'], false, 'red', 'Italy', 'approved'),
  ('GROS VERT BLANC', NULL, false, 'white', 'France', 'approved'),
  ('GUARDAVALLE', ARRAY['UVA GRECA'], false, 'white', 'Italy', 'approved'),
  ('GUTENBORNER', NULL, false, 'white', 'Germany', 'approved'),
  ('HANS', NULL, false, 'white', 'Czech Republic', 'approved'),
  ('HARSLEVELUE', NULL, false, 'white', 'Hungary', 'approved'),
  ('HECKER', NULL, false, 'white', 'Germany', 'approved'),
  ('HEGEL', NULL, false, 'red', 'Germany', 'approved'),
  ('HELFENSTEINER', NULL, false, 'red', 'Germany', 'approved'),
  ('HELIOS', NULL, false, 'white', 'Germany', 'approved'),
  ('HEROLDREBE', NULL, false, 'red', 'Germany', 'approved'),
  ('HEUNISCH WEISS', ARRAY['HEUNISCH'], false, 'white', NULL, 'approved'),
  ('HIBERNAL', NULL, true, 'white', 'Czech Republic', 'approved'),
  ('HOELDER', NULL, false, 'white', 'Germany', 'approved'),
  ('HUXELREBE', ARRAY['HUXEL'], false, 'white', 'Germany', 'approved'),
  ('IMPIGNO', NULL, false, 'white', 'Italy', 'approved'),
  ('INVERNENGA', NULL, false, 'white', 'Italy', 'approved'),
  ('IORDAN', NULL, false, 'white', 'Romania', 'approved'),
  ('IRSAI OLIVER', NULL, false, 'white', 'Czech Republic', 'approved'),
  ('ITALICA', NULL, false, 'white', 'Italy', 'approved'),
  ('IZSAKI SARFEHER', NULL, false, 'white', 'Hungary', 'approved'),
  ('JACQUERE', NULL, false, 'white', 'Portugal', 'approved'),
  ('JAEN TINTO', NULL, false, 'red', 'Spain', 'approved'),
  ('JAKOB GERHARDT BLANC', NULL, false, 'white', 'Spain', 'approved'),
  ('JAMPAL', NULL, false, 'white', 'Portugal', 'approved'),
  ('JOHANNITER', NULL, false, 'white', 'Germany', 'approved'),
  ('JOUBERTIN', NULL, false, 'red', 'France', 'approved'),
  ('JUBILAEUMSREBE', NULL, false, 'other', 'Austria', 'approved'),
  ('JUBILEUM 75', NULL, false, 'white', 'Hungary', 'approved'),
  ('JUHFARK', NULL, false, 'white', 'Hungary', 'approved'),
  ('JURANCON BLANC', NULL, false, 'white', 'France', 'approved'),
  ('JURANCON NOIR', ARRAY['DAME NOIRE N'], false, 'red', 'France', 'approved'),
  ('JUWEL', NULL, false, 'white', 'Germany', 'approved'),
  ('KABAR', NULL, false, 'white', 'Hungary', 'approved'),
  ('KADARKA KEK', NULL, false, 'red', 'Romania', 'approved'),
  ('KAKOTRYGIS', NULL, false, 'white', 'Greece', 'approved'),
  ('KANZLER', NULL, false, 'white', 'Germany', 'approved'),
  ('KARABRAIMIS', NULL, false, 'red', 'Greece', 'approved'),
  ('KARAT', NULL, false, 'white', 'Hungary', 'approved'),
  ('KARMIN', NULL, false, 'red', 'Hungary', 'approved'),
  ('KARTSIOTIS', NULL, false, 'red', 'Greece', 'approved'),
  ('KATSAKOULIAS', NULL, false, 'red', 'Greece', 'approved'),
  ('KATSANO', NULL, false, 'white', 'Greece', 'approved'),
  ('KEKNYELUE', NULL, false, 'white', 'Hungary', 'approved'),
  ('KERATUDA', NULL, false, 'red', 'Greece', 'approved'),
  ('KERNER', NULL, false, 'white', 'Czech Republic', 'approved'),
  ('KERNLING', NULL, false, 'white', 'Germany', 'approved'),
  ('KNIPPERLE', NULL, false, 'white', 'France', 'approved'),
  ('KOENIGIN DER WEINGAERTEN', NULL, false, 'white', 'Italy', 'approved'),
  ('KOEVIDINKA', NULL, false, 'white', 'Hungary', 'approved'),
  ('KOINIARIKO', NULL, false, 'red', 'Greece', 'approved'),
  ('KOKKINOVOSTITSA', NULL, false, 'red', 'Greece', 'approved'),
  ('KOLLINIATIKO', NULL, false, 'red', 'Greece', 'approved'),
  ('KONTOKLADI LEFKO', NULL, false, 'white', 'Greece', 'approved'),
  ('KORAI BIBOR', NULL, true, 'red', 'Hungary', 'approved'),
  ('KORINTHIAKI LEFKI', NULL, false, 'white', 'Italy', 'approved'),
  ('KORINTHIAKI MAVRO', NULL, false, 'red', 'Italy', 'approved'),
  ('KORITHI ASPRO', NULL, false, 'white', 'Greece', 'approved'),
  ('KORITHI MAVRO', NULL, false, 'red', 'Greece', 'approved'),
  ('KORITSANOS MAVROS', NULL, false, 'red', 'Greece', 'approved'),
  ('KORONA', NULL, false, 'white', 'Hungary', 'approved'),
  ('KOTSIFALI', NULL, false, 'red', 'Greece', 'approved'),
  ('KOTSIFOLIATIKO', NULL, false, 'red', 'Greece', 'approved'),
  ('KOUKOULI', NULL, false, 'white', 'Greece', 'approved'),
  ('KOUMARI', NULL, false, 'red', 'Greece', 'approved'),
  ('KOUMIOTIS', NULL, false, 'white', 'Greece', 'approved'),
  ('KOUTSOUMBELI', NULL, false, 'rosé', 'Greece', 'approved'),
  ('KOZANITIS', NULL, false, 'white', 'Greece', 'approved'),
  ('KRASSATO', NULL, false, 'red', 'Greece', 'approved'),
  ('KREACA', NULL, false, 'white', 'Romania', 'approved'),
  ('KRETIKO LEFKO', NULL, false, 'white', 'Greece', 'approved'),
  ('KUNLEANY', NULL, true, 'white', 'Hungary', 'approved'),
  ('KYDONITSA', NULL, false, 'white', 'Greece', 'approved'),
  ('LABRUSCO', NULL, false, 'red', 'Portugal', 'approved'),
  ('LACRIMA', NULL, false, 'red', 'Italy', 'approved'),
  ('LADIKINO', NULL, false, 'red', 'Greece', 'approved'),
  ('LADO', NULL, false, 'white', 'Spain', 'approved'),
  ('LAGARINO BIANCO', NULL, false, 'white', 'Italy', 'approved'),
  ('LAGORTHI', NULL, false, 'white', 'Greece', 'approved'),
  ('LAGREIN', NULL, false, 'red', 'Bulgaria', 'approved'),
  ('LAMBRUSCA DI ALESSANDRIA', NULL, false, 'red', 'Italy', 'approved'),
  ('LAMBRUSCO A FOGLIA FRASTAGLIATA', ARRAY['ENANTIO'], false, 'red', 'Italy', 'approved'),
  ('LAMBRUSCO BARGHI', NULL, false, 'red', 'Italy', 'approved'),
  ('LAMBRUSCO DI SORBARA', NULL, false, 'red', 'Italy', 'approved'),
  ('LAMBRUSCO GRASPAROSSA', ARRAY['GROPPELLO GRASPAROSSA', 'LAMBRUSCO*'], false, 'red', 'Italy', 'approved'),
  ('LAMBRUSCO MAESTRI', ARRAY['GROPPELLO MAESTRI', 'LAMBRUSCO*'], false, 'red', 'Italy', 'approved'),
  ('LAMBRUSCO MARANI', ARRAY['LAMBRUSCO*'], false, 'red', 'Italy', 'approved'),
  ('LAMBRUSCO MONTERICCO', NULL, false, 'red', 'Italy', 'approved'),
  ('LAMBRUSCO OLIVA', NULL, false, 'red', 'Italy', 'approved'),
  ('LAMBRUSCO SALAMINO', ARRAY['LAMBRUSCO*'], false, 'red', 'Italy', 'approved'),
  ('LAMBRUSCO VIADANESE', ARRAY['GROPPELLO RUBERTI'], false, 'red', 'Italy', 'approved'),
  ('LAMEIRO', NULL, false, 'white', 'Portugal', 'approved'),
  ('LANDAL', ARRAY['244 LANDOT'], true, 'red', 'France', 'approved'),
  ('LARIAO', NULL, false, 'white', 'Portugal', 'approved'),
  ('LAUROT', NULL, true, 'red', 'Czech Republic', 'approved'),
  ('LAUZET', NULL, false, 'white', 'France', 'approved'),
  ('LECINARO', NULL, false, 'red', 'Italy', 'approved'),
  ('LEIRA', NULL, false, 'white', 'Portugal', 'approved'),
  ('LEN DE L''EL', ARRAY['LOIN DE L''ŒIL B'], false, 'white', 'France', 'approved'),
  ('LENA', NULL, false, 'white', 'Czech Republic', 'approved'),
  ('LEON MILLOT', ARRAY['194-2 KUHLMANN'], true, 'red', 'France', 'approved'),
  ('LIATIKO', NULL, false, 'red', 'Greece', 'approved'),
  ('LILIORILA', NULL, false, 'white', 'France', 'approved'),
  ('LIMNIO', NULL, false, 'red', 'Greece', 'approved'),
  ('LIMNIONA', NULL, false, 'red', 'Greece', 'approved'),
  ('LISTAN PRIETO', ARRAY['ALMUñECO'], false, 'red', 'Spain', 'approved'),
  ('LISTRAO ROXO', NULL, false, 'red', 'Portugal', 'approved'),
  ('LIVAL', NULL, false, 'red', 'France', 'approved'),
  ('LOUREIRO BLANCO', ARRAY['LOUREIRO BLANCO'], false, 'white', 'Spain', 'approved'),
  ('LOURELA', NULL, false, 'red', 'Portugal', 'approved'),
  ('LUMASSINA', ARRAY['BUZZETTO', 'MATAOSSO', 'MATAOSSU'], false, 'white', 'Italy', 'approved'),
  ('LUSITANO', NULL, false, 'red', 'Portugal', 'approved'),
  ('LUZIDIO', NULL, false, 'white', 'Portugal', 'approved'),
  ('MACERATINO', ARRAY['RIBONA'], false, 'white', 'Italy', 'approved'),
  ('MAGLIOCCO CANINO', NULL, false, 'red', 'Italy', 'approved'),
  ('MAGLIOCCO DOLCE', ARRAY['NERELLO MANTELLATO'], false, 'red', 'Italy', 'approved'),
  ('MAIOLICA', NULL, false, 'red', 'Italy', 'approved'),
  ('MAIOLINA', NULL, false, 'red', 'Italy', 'approved'),
  ('MALAGOUZIA', NULL, false, 'white', 'Greece', 'approved'),
  ('MALANDRA', NULL, false, 'red', 'Portugal', 'approved'),
  ('MALBO GENTILE', NULL, false, 'red', 'Italy', 'approved'),
  ('MALINGRE PRECOCE', ARRAY['MALINGER'], false, 'white', NULL, 'approved'),
  ('MALOUKATO', NULL, false, 'white', 'Greece', 'approved'),
  ('MALVAR', NULL, false, 'white', 'Spain', 'approved'),
  ('MALVARISCO', NULL, false, 'red', 'Portugal', 'approved'),
  ('MALVASIA', NULL, false, 'white', 'Portugal', 'approved'),
  ('MALVASIA BIANCA', NULL, false, 'white', 'Portugal', 'approved'),
  ('MALVASIA BIANCA DI BASILICATA', NULL, false, 'white', 'Italy', 'approved'),
  ('MALVASIA BIANCA LUNGA', ARRAY['MALVASIA *', 'MALVOISIE**', 'MALVOISIER**'], false, 'white', 'Italy', 'approved'),
  ('MALVASIA BRANCA DE SAO JORGE', NULL, false, 'white', 'Portugal', 'approved'),
  ('MALVASIA DEL LAZIO', ARRAY['MALVASIA PUNTINATA'], false, 'white', 'Italy', 'approved'),
  ('MALVASIA DI CANDIA AROMATICA', NULL, false, 'white', 'Italy', 'approved'),
  ('MALVASIA DI CASORZO', NULL, false, 'red', 'Italy', 'approved'),
  ('MALVASIA DI SARDEGNA ROSADA', NULL, false, 'red', 'Spain', 'approved'),
  ('MALVASIA DI SCHIERANO', NULL, false, 'red', 'Italy', 'approved'),
  ('MALVASIA DUBROVACKA', ARRAY['MALVASíA DE SITGES', 'MALVASíA DE BANYALBUFAR'], false, 'white', 'Spain', 'approved'),
  ('MALVASIA FINA', ARRAY['BOAL(4)'], false, 'white', 'Portugal', 'approved'),
  ('MALVASIA FINA ROXA', NULL, false, 'red', 'Portugal', 'approved'),
  ('MALVASIA ISTRIANA', NULL, false, 'white', 'Italy', 'approved'),
  ('MALVASIA NERA DI BASILICATA', NULL, false, 'red', 'Italy', 'approved'),
  ('MALVASIA NERA DI BRINDISI', ARRAY['MALVASIA *', 'MALVOISIE**', 'MALVOISIER**'], false, 'red', 'Italy', 'approved'),
  ('MALVASIA NERA LUNGA', NULL, false, 'red', 'Italy', 'approved'),
  ('MALVASIA PARDA', NULL, false, 'white', 'Portugal', 'approved'),
  ('MALVASIA PRETA', NULL, false, 'red', 'Portugal', 'approved'),
  ('MALVASIA ROMANA', NULL, false, 'white', 'Portugal', 'approved'),
  ('MALVASIA ROSA', NULL, false, 'rosé', 'Italy', 'approved'),
  ('MALVASIA VOLCANICA', NULL, false, 'white', 'Spain', 'approved'),
  ('MALVERINA', NULL, true, 'white', 'Czech Republic', 'approved'),
  ('MALVIA', NULL, false, 'white', 'Portugal', 'approved'),
  ('MALVOEIRA', NULL, false, 'white', 'Portugal', 'approved'),
  ('MAMAIA', NULL, false, 'red', 'Romania', 'approved'),
  ('MANCIN', NULL, false, 'red', 'France', 'approved'),
  ('MANDILARIA', ARRAY['AMORGIANO', 'DOUMBRENA MAVRI', 'KOUNTOURA MAVRI'], false, 'red', 'Greece', 'approved'),
  ('MANSENG GROS BLANC', NULL, false, 'white', 'Spain', 'approved'),
  ('MANSENG NOIR', NULL, false, 'red', 'France', 'approved'),
  ('MANSENG PETIT BLANC', NULL, false, 'white', 'Spain', 'approved'),
  ('MANTEUDO', NULL, false, 'white', 'Portugal', 'approved'),
  ('MANTEUDO PRETO', NULL, false, 'red', 'Portugal', 'approved'),
  ('MANTO NEGRO', NULL, false, 'red', 'Spain', 'approved'),
  ('MANZONI  2- 15', ARRAY['MANZONI ROSSO*'], false, 'red', 'Italy', 'approved'),
  ('MANZONI BIANCO', ARRAY['INCROCIO MANZONI 6.0.13'], false, 'white', 'Italy', 'approved'),
  ('MANZONI MOSCATO', ARRAY['INCROCIO MANZONI 13.0.25'], false, 'red', 'Italy', 'approved'),
  ('MANZONI ROSA', ARRAY['INCROCIO MANZONI 1-50'], false, 'rosé', 'Italy', 'approved'),
  ('MAOR', NULL, false, 'white', 'Italy', 'approved'),
  ('MARECHAL FOCH', ARRAY['188-2 KUHLMANN'], true, 'red', 'France', 'approved'),
  ('MARFAL', NULL, false, 'white', 'Spain', 'approved'),
  ('MARIENSTEINER', NULL, false, 'white', 'Germany', 'approved'),
  ('MARQUINHAS', NULL, false, 'white', 'Portugal', 'approved'),
  ('MARSANNE', NULL, false, 'white', 'Bulgaria', 'approved'),
  ('MARSELAN', NULL, false, 'red', 'Bulgaria', 'approved'),
  ('MARSIGLIANA NERA', NULL, false, 'red', 'Italy', 'approved'),
  ('MARUFO', NULL, false, 'red', 'Portugal', 'approved'),
  ('MARZEMINA BIANCA', ARRAY['MARZEMINA*'], false, 'white', 'Italy', 'approved'),
  ('MARZEMINO', ARRAY['BERZAMINO', 'BERZEMINO'], false, 'red', 'Italy', 'approved'),
  ('MATURANA BLANCA', NULL, false, 'white', 'Spain', 'approved'),
  ('MAUZAC BLANC', NULL, false, 'white', 'France', 'approved'),
  ('MAUZAC ROSE', NULL, false, 'rosé', 'France', 'approved'),
  ('MAVRODAPHNI', NULL, false, 'red', 'Greece', 'approved'),
  ('MAVROKORAKAS', ARRAY['MAVROKOKORAS'], false, 'red', 'Greece', 'approved'),
  ('MAVROTHIRIKO', NULL, false, 'red', 'Greece', 'approved'),
  ('MAVROTRAGANO', NULL, false, 'red', 'Greece', 'approved'),
  ('MAVROUDI', NULL, false, 'red', 'Greece', 'approved'),
  ('MAVROUDI CHONDRO KALAVRYTON', NULL, false, 'red', 'Greece', 'approved'),
  ('MAVROUDIA', NULL, false, 'red', 'Greece', 'approved'),
  ('MAVRUD', ARRAY['??????'], false, 'red', 'Bulgaria', 'approved'),
  ('MAYOLET', NULL, false, 'red', 'Italy', 'approved'),
  ('MAZZESE', NULL, false, 'red', 'Italy', 'approved'),
  ('MEDINA', NULL, true, 'red', 'Hungary', 'approved'),
  ('MEDOC NOIR', ARRAY['MéDOC NOIR'], false, 'red', 'Hungary', 'approved'),
  ('MELARA', NULL, false, 'white', 'Italy', 'approved'),
  ('MELHORIO', NULL, false, 'red', 'Portugal', 'approved'),
  ('MELON', NULL, false, 'white', 'Bulgaria', 'approved'),
  ('MELRA', NULL, false, 'red', 'Portugal', 'approved'),
  ('MENCIA', NULL, false, 'red', 'Portugal', 'approved'),
  ('MERILLE', NULL, false, 'red', 'France', 'approved'),
  ('MERLESE', NULL, false, 'red', 'Italy', 'approved'),
  ('MERLOT BLANC', NULL, false, 'white', 'France', 'approved'),
  ('MERLOT NOIR', NULL, false, 'red', 'Czech Republic', 'approved'),
  ('MERSEGUERA', ARRAY['EXQUITSAGOS', 'VERDOSILLA'], false, 'white', 'Spain', 'approved'),
  ('MERZLING', NULL, false, 'white', 'Germany', 'approved'),
  ('MESLIER PETIT', NULL, false, 'white', 'France', 'approved'),
  ('MESLIER SAINT FRANCOIS', ARRAY['GROS MESLIER B'], false, 'white', 'France', 'approved'),
  ('MESSENIKOLA MAVRO', NULL, false, 'red', 'Greece', 'approved'),
  ('MILGRANET', NULL, false, 'red', 'France', 'approved'),
  ('MILIA', NULL, false, 'rosé', 'Czech Republic', 'approved'),
  ('MINDELO', NULL, false, 'red', 'Portugal', 'approved'),
  ('MINELLA BIANCA', NULL, false, 'white', 'Italy', 'approved'),
  ('MIORITA', NULL, false, 'white', 'Romania', 'approved'),
  ('MISKET CHERVEN', ARRAY['?????? ??????', 'SUNGURLARE MUSCAT', '??????????? ??????'], false, 'white', 'Bulgaria', 'approved'),
  ('MISKET KAILASHKI', ARRAY['?????? ????????'], false, 'white', 'Bulgaria', 'approved'),
  ('MISKET MARKOVSKI', ARRAY['?????? ?????????'], false, 'white', 'Bulgaria', 'approved'),
  ('MISKET SANDANSKI', ARRAY['?????? ?????????'], false, 'white', 'Bulgaria', 'approved'),
  ('MISKET VARNENSKI', ARRAY['????????? ??????'], false, 'white', 'Bulgaria', 'approved'),
  ('MOLAR', NULL, false, 'red', 'Portugal', 'approved'),
  ('MOLDOVA', ARRAY['???????'], true, 'red', 'Bulgaria', 'approved'),
  ('MOLETTE', NULL, false, 'white', 'France', 'approved'),
  ('MOLINARA', ARRAY['ROSSANO', 'ROSSANELLA'], false, 'red', 'Italy', 'approved'),
  ('MOLINERA', NULL, false, 'red', 'Spain', 'approved'),
  ('MOLLAR CANO', ARRAY['MULATA'], false, 'red', 'Spain', 'approved'),
  ('MOLLARD', NULL, false, 'red', 'France', 'approved'),
  ('MONARCH', NULL, false, 'red', 'Germany', 'approved'),
  ('MONASTRELL', NULL, false, 'red', 'Spain', 'approved'),
  ('MONDEUSE BLANCHE', NULL, false, 'white', 'France', 'approved'),
  ('MONDEUSE NOIRE', NULL, false, 'red', 'France', 'approved'),
  ('MONEMVASSIA', ARRAY['MONOVASIA MONOMVASITIKO'], false, 'white', 'Greece', 'approved'),
  ('MONERAC', NULL, false, 'red', 'France', 'approved'),
  ('MONICA NERA', NULL, false, 'red', 'Italy', 'approved'),
  ('MONTEPULCIANO', NULL, false, 'red', 'Bulgaria', 'approved'),
  ('MONTILS', NULL, false, 'white', 'France', 'approved'),
  ('MONTONICO BIANCO', ARRAY['MONTONICO*', 'MANTONICO *'], false, 'white', 'Italy', 'approved'),
  ('MONTU', ARRAY['MONTUNI'], false, 'white', 'Italy', 'approved'),
  ('MONVEDRO', NULL, false, 'red', 'Portugal', 'approved'),
  ('MOPR', ARRAY['MOPR'], false, 'white', 'Czech Republic', 'approved'),
  ('MORADELLA', NULL, false, 'red', 'Italy', 'approved'),
  ('MORAVIA AGRIA', NULL, false, 'red', 'Spain', 'approved'),
  ('MORAVIA DULCE', NULL, false, 'white', 'Italy', 'approved'),
  ('MORETO', NULL, false, 'red', 'Portugal', 'approved'),
  ('MORIO MUSKAT', NULL, false, 'white', 'Germany', 'approved'),
  ('MORISTEL', ARRAY['JUAN IBáñEZ', 'CONCEJóN'], false, 'red', 'Spain', 'approved'),
  ('MORNASCA', NULL, false, 'red', 'Italy', 'approved'),
  ('MORONE', NULL, false, 'red', 'Italy', 'approved'),
  ('MORRASTEL BOUSCHET', NULL, false, 'red', 'Spain', 'approved'),
  ('MOSCARGO', NULL, false, 'red', 'Portugal', 'approved'),
  ('MOSCATEL FAUSTINO', NULL, false, 'white', 'Portugal', 'approved'),
  ('MOSCATEL FINO', NULL, false, 'white', 'Portugal', 'approved'),
  ('MOSCATEL LILAZ', NULL, false, 'white', 'Portugal', 'approved'),
  ('MOSCATEL NUNES', NULL, false, 'white', 'Portugal', 'approved'),
  ('MOSCATELLO SELVATICO', NULL, false, 'white', 'Italy', 'approved'),
  ('MOSCATO DI SCANZO', NULL, false, 'red', 'Italy', 'approved'),
  ('MOSCATO DI TERRACINA', ARRAY['MOSCATELLO*', 'MOSCATELLONE*', 'MUSCAT**', 'MUSKATELLER**'], false, 'white', 'Italy', 'approved'),
  ('MOSCATO GIALLO', ARRAY['GELBER MUSKATELLER', 'MOSCATO*', 'MOSCATELLO*', 'MOSCATELLONE*', 'GOLDMUSKATELLER**', 'MUSCAT***', 'MUSKATELLER***'], false, 'white', 'Italy', 'approved'),
  ('MOSCATO NERO DI ACQUI', NULL, false, 'red', 'Italy', 'approved'),
  ('MOSCHARDINA', ARRAY['MOSCHARDINIA'], false, 'white', 'Greece', 'approved'),
  ('MOSCHATO MAVRO', NULL, false, 'red', 'Greece', 'approved'),
  ('MOSCHATO TRANI', NULL, false, 'white', 'Greece', 'approved'),
  ('MOSCHOFILERO', ARRAY['FILERI'], false, 'rosé', 'Greece', 'approved'),
  ('MOSTOSA', NULL, false, 'white', 'Italy', 'approved'),
  ('MOUCHTOURI', NULL, false, 'red', 'Greece', 'approved'),
  ('MOUDIATIKO', NULL, false, 'red', 'Greece', 'approved'),
  ('MOURATON', ARRAY['MOURATON'], false, 'red', 'Spain', 'approved'),
  ('MOURISCO DE SEMENTE', NULL, false, 'red', 'Portugal', 'approved'),
  ('MOURISCO DE TREVOES', NULL, false, 'red', 'Portugal', 'approved'),
  ('MOURVAISON', NULL, false, 'red', 'France', 'approved'),
  ('MOUYSSAGUES', NULL, false, 'red', 'France', 'approved'),
  ('MUELLER THURGAU WEISS', ARRAY['RIESLING X SYLVANER*'], false, 'white', 'Italy', 'approved'),
  ('MULATA', NULL, false, 'red', 'Portugal', 'approved'),
  ('MUSCADELLE', NULL, false, 'white', 'Romania', 'approved'),
  ('MUSCARDIN', NULL, false, 'red', 'France', 'approved'),
  ('MUSCAT A PETITS GRAINS BLANCS', ARRAY['MOSCATO', 'MUSCAT', 'MUSCAT BLANC', 'MUSKATELLER'], false, 'white', 'Germany', 'approved'),
  ('MUSCAT A PETITS GRAINS NOIRS', NULL, false, 'red', 'Portugal', 'approved'),
  ('MUSCAT A PETITS GRAINS ROSES', NULL, false, 'red', 'Spain', 'approved'),
  ('MUSCAT A PETITS GRAINS ROUGES', NULL, false, 'other', 'Romania', 'approved'),
  ('MUSCAT CENDRE', NULL, false, 'white', 'France', 'approved'),
  ('MUSCAT HAMBURG', NULL, false, 'red', 'Hungary', 'approved'),
  ('MUSCAT OF ALEXANDRIA', ARRAY['MOSCATEL DE MáLAGA'], false, 'white', 'Spain', 'approved'),
  ('MUSCAT OTTONEL', NULL, false, 'white', 'Italy', 'approved'),
  ('MUSTOASA DE MADERAT', NULL, false, 'white', 'Romania', 'approved'),
  ('MYGDALI', NULL, false, 'white', 'Greece', 'approved'),
  ('NAIA', NULL, false, 'white', 'Portugal', 'approved'),
  ('NASCETTA', NULL, false, 'white', 'Italy', 'approved'),
  ('NASCO', NULL, false, 'white', 'Italy', 'approved'),
  ('NEBBIERA', NULL, false, 'red', 'Italy', 'approved'),
  ('NEBBIOLO', NULL, false, 'red', 'Bulgaria', 'approved'),
  ('NEGOSKA', NULL, false, 'red', 'Greece', 'approved'),
  ('NEGRARA TRENTINA', NULL, false, 'red', 'Italy', 'approved'),
  ('NEGRET DE BANHARS', NULL, false, 'red', 'France', 'approved'),
  ('NEGRETTE', NULL, false, 'red', 'France', 'approved'),
  ('NEGRETTO', NULL, false, 'red', 'Italy', 'approved'),
  ('NEGRO AMARO', NULL, false, 'red', 'Greece', 'approved'),
  ('NEGRO AMARO PRECOCE', NULL, false, 'red', 'Italy', 'approved'),
  ('NEGRU AROMAT', NULL, false, 'red', 'Romania', 'approved'),
  ('NEGRU DE DRAGASANI', NULL, false, 'red', 'Romania', 'approved'),
  ('NEKTAR', NULL, false, 'white', 'Hungary', 'approved'),
  ('NERELLO MASCALESE', NULL, false, 'red', 'Italy', 'approved'),
  ('NERETTA CUNEESE', NULL, false, 'red', 'Italy', 'approved'),
  ('NERETTO DI BAIRO', NULL, false, 'red', 'Italy', 'approved'),
  ('NERO', NULL, true, 'red', 'Hungary', 'approved'),
  ('NERO BUONO DI CORI', NULL, false, 'red', 'Italy', 'approved'),
  ('NERONET', NULL, false, 'red', 'Germany', 'approved'),
  ('NEUBURGER', NULL, false, 'other', 'Austria', 'approved'),
  ('NEVOEIRA', NULL, false, 'red', 'Portugal', 'approved'),
  ('NEYRET', NULL, false, 'red', 'Italy', 'approved'),
  ('NIEDDERA', NULL, false, 'red', 'Italy', 'approved'),
  ('NIEDDU MANNU', ARRAY['MORESCONO N'], false, 'red', 'France', 'approved'),
  ('NIGRA', NULL, false, 'red', 'Italy', 'approved'),
  ('NITRANKA', NULL, false, 'red', 'Czech Republic', 'approved'),
  ('NOBLING', NULL, false, 'white', 'Germany', 'approved'),
  ('NOCERA', NULL, false, 'red', 'Italy', 'approved'),
  ('NORIA', NULL, false, 'white', 'Czech Republic', 'approved'),
  ('NOSIOLA', NULL, false, 'white', 'Italy', 'approved'),
  ('NOTARDOMENICO', NULL, false, 'red', 'Italy', 'approved'),
  ('NOVAC', NULL, false, 'red', 'Romania', 'approved'),
  ('NURAGUS', NULL, false, 'white', 'Italy', 'approved'),
  ('OANA', NULL, false, 'white', 'Romania', 'approved'),
  ('OBERLIN NOIR', ARRAY['595 OBERLIN'], true, 'red', 'France', 'approved'),
  ('ODYSSEUS', NULL, true, 'white', 'Hungary', 'approved'),
  ('OLIVIA', NULL, false, 'red', 'Romania', 'approved'),
  ('ONDARRABI BELTZA', NULL, false, 'red', 'Spain', 'approved'),
  ('ONDENC', NULL, false, 'white', 'France', 'approved'),
  ('OPSIMOS EDESSIS', ARRAY['AMASSI : KARATZOVAS', 'FOUSTANI'], false, 'white', 'Greece', 'approved'),
  ('OPSIMOS SOUFLIOU', NULL, false, 'white', 'Greece', 'approved'),
  ('OPTIMA', NULL, false, 'white', 'Germany', 'approved'),
  ('ORION', NULL, true, 'white', 'Czech Republic', 'approved'),
  ('ORLEANS GELB', ARRAY['ORLEANS'], false, 'white', NULL, 'approved'),
  ('ORPHEUS', NULL, true, 'white', 'Hungary', 'approved'),
  ('ORPICCHIO', NULL, false, 'white', 'Italy', 'approved'),
  ('ORTEGA', NULL, false, 'white', 'Germany', 'approved'),
  ('ORTRUGO', NULL, false, 'white', 'Italy', 'approved'),
  ('OSELETA', NULL, false, 'red', 'Italy', 'approved'),
  ('OSTEINER', NULL, false, 'white', 'Germany', 'approved'),
  ('OZANA', NULL, false, 'white', 'Romania', 'approved'),
  ('PADEIRO', NULL, false, 'red', 'Portugal', 'approved'),
  ('PALAS', NULL, false, 'red', 'Germany', 'approved'),
  ('PALAVA', NULL, false, 'rosé', 'Czech Republic', 'approved'),
  ('PALLAGRELLO NERO', NULL, false, 'red', 'Italy', 'approved'),
  ('PALOMINO DE JEREZ', ARRAY['JEREZ'], false, 'white', 'Spain', 'approved'),
  ('PALOMINO FINO', NULL, false, 'white', 'France', 'approved'),
  ('PAMID BIAL', ARRAY['?????'], false, 'white', 'Bulgaria', 'approved'),
  ('PAMPANARO', NULL, false, 'white', 'Italy', 'approved'),
  ('PANNON FRANKOS', NULL, false, 'red', 'Hungary', 'approved'),
  ('PAPADIKO', NULL, false, 'red', 'Greece', 'approved'),
  ('PARDILLO', ARRAY['MARISANCHO'], false, 'white', 'Spain', 'approved'),
  ('PARELLADA', ARRAY['MONTONEC', 'MONTONEGA'], false, 'white', 'Spain', 'approved'),
  ('PARRALETA', NULL, false, 'red', 'Spain', 'approved'),
  ('PARREIRA MATIAS', NULL, false, 'red', 'Portugal', 'approved'),
  ('PASCAL BLANC', NULL, false, 'white', 'France', 'approved'),
  ('PASCALE DI CAGLIARI', NULL, false, 'red', 'Italy', 'approved'),
  ('PASSAU', NULL, false, 'red', 'Italy', 'approved'),
  ('PATORRA', NULL, false, 'red', 'Portugal', 'approved'),
  ('PATRIA', NULL, false, 'white', 'Hungary', 'approved'),
  ('PATRINO', NULL, false, 'red', 'Greece', 'approved'),
  ('PAVANA', NULL, false, 'red', 'Italy', 'approved'),
  ('PECORELLO', NULL, false, 'red', 'Italy', 'approved'),
  ('PECORINO', ARRAY['VISSANELLO'], false, 'white', 'Italy', 'approved'),
  ('PEDRAL', NULL, false, 'red', 'Spain', 'approved'),
  ('PEDRO XIMENEZ', NULL, false, 'white', 'Spain', 'approved'),
  ('PELAVERGA', ARRAY['CARI'], false, 'red', 'Italy', 'approved'),
  ('PELAVERGA PICCOLO', NULL, false, 'red', 'Italy', 'approved'),
  ('PELSO', NULL, false, 'white', 'Hungary', 'approved'),
  ('PENSAL BLANCA', ARRAY['PENSAL BLANCA', 'PRENSAL'], false, 'white', 'Spain', 'approved'),
  ('PERDEA', NULL, false, 'white', 'France', 'approved'),
  ('PERERA (VALDOBBIADENE)', NULL, false, 'white', 'Italy', 'approved'),
  ('PERIGO', NULL, false, 'white', 'Portugal', 'approved'),
  ('PERLA DEI VIVI', NULL, false, 'red', 'Italy', 'approved'),
  ('PERLE', NULL, false, 'rosé', 'Germany', 'approved'),
  ('PERO PINHAO', NULL, false, 'red', 'Portugal', 'approved'),
  ('PERRICONE', ARRAY['PIGNATELLO'], false, 'red', 'Italy', 'approved'),
  ('PERRUM BRANCO', NULL, false, 'white', 'Portugal', 'approved'),
  ('PERRUNO', NULL, false, 'white', 'Spain', 'approved'),
  ('PERSAN', NULL, false, 'red', 'Italy', 'approved'),
  ('PETIT ROUGE', NULL, false, 'red', 'Italy', 'approved'),
  ('PETROKORITHO LEFKO', NULL, false, 'white', 'Greece', 'approved'),
  ('PETROULIANOS', NULL, false, 'white', 'Greece', 'approved'),
  ('PEXEM', NULL, false, 'red', 'Portugal', 'approved'),
  ('PHOENIX', ARRAY['PHöNIX'], false, 'white', 'Germany', 'approved'),
  ('PICCOLA NERA', NULL, false, 'red', 'Italy', 'approved'),
  ('PICOLIT', NULL, false, 'white', 'Italy', 'approved'),
  ('PICOLIT NERO', NULL, false, 'red', 'Italy', 'approved'),
  ('PIEDIROSSO', ARRAY['PIEDE DI COLOMBO', 'PIEDE DI PALUMBO', 'PER'' E PALUMMO', 'PALOMBINA'], false, 'red', 'Italy', 'approved'),
  ('PIGNOLA VALTELLINESE', NULL, false, 'red', 'Italy', 'approved'),
  ('PIGNOLO', NULL, false, 'red', 'Italy', 'approved'),
  ('PILONGO', NULL, false, 'red', 'Portugal', 'approved'),
  ('PINEAU D''AUNIS', NULL, false, 'red', 'France', 'approved'),
  ('PINELLA', ARRAY['PINELLA BIANCA', 'PINELLO'], false, 'white', 'Italy', 'approved'),
  ('PINOT BLANC', NULL, false, 'white', 'Bulgaria', 'approved'),
  ('PINOT GRIS', ARRAY['PINOT GRIS', 'RULäNDER'], false, 'other', 'Austria', 'approved'),
  ('PINOT MEUNIER', NULL, false, 'red', 'Bulgaria', 'approved'),
  ('PINOT NOIR', ARRAY['BLAUER SPäTBURGUNDER', 'PINOT NOIR'], false, 'other', 'Austria', 'approved'),
  ('PINOT PRECOCE NOIR', ARRAY['FRüHBURGUNDER', 'MADELEINE NOIR', 'PINOT MADELEINE', 'PINOT NOIR PRECOCE'], false, 'red', 'Germany', 'approved'),
  ('PINOTIN', NULL, true, 'red', 'Germany', 'approved'),
  ('PIQUEPOUL BLANC', NULL, false, 'white', 'France', 'approved'),
  ('PIQUEPOUL GRIS', NULL, false, 'white', 'France', 'approved'),
  ('PIQUEPOUL NOIR', NULL, false, 'red', 'Portugal', 'approved'),
  ('PIROSO', NULL, false, 'red', 'Germany', 'approved'),
  ('PLANT DE BRUNEL', NULL, false, 'red', 'France', 'approved'),
  ('PLANT DE COUSTON', NULL, false, 'red', 'France', 'approved'),
  ('PLANT DROIT', ARRAY['ESPANENC N'], false, 'red', 'France', 'approved'),
  ('PLANTA FINA', NULL, false, 'white', 'Portugal', 'approved'),
  ('PLANTA NOVA', ARRAY['TARDANA', 'TORTOZóN'], false, 'white', 'Spain', 'approved'),
  ('PLANTET', ARRAY['5455 SEIBEL'], true, 'red', 'France', 'approved'),
  ('PLASSA', NULL, false, 'red', 'Italy', 'approved'),
  ('PLATANIA', NULL, false, 'white', 'Greece', 'approved'),
  ('PLAVAIE', NULL, false, 'white', 'Romania', 'approved'),
  ('PLEVENSKI KOLORIT', ARRAY['????????? ???????'], false, 'red', 'Bulgaria', 'approved'),
  ('PLINIANA', NULL, false, 'red', 'Italy', 'approved'),
  ('PLITO', NULL, false, 'white', 'Greece', 'approved'),
  ('POELOESKE MUSKOTALY', NULL, true, 'white', 'Romania', 'approved'),
  ('POLLERA NERA', NULL, false, 'red', 'Italy', 'approved'),
  ('PORTAN', NULL, false, 'red', 'France', 'approved'),
  ('PORTUGIESER BLAU', NULL, false, 'other', 'Austria', 'approved'),
  ('PORTUGIESER GRUEN', NULL, false, 'white', 'Czech Republic', 'approved'),
  ('PORTUGIESER ROT', NULL, false, 'white', 'Czech Republic', 'approved'),
  ('POTAMISSI ASPRO', NULL, false, 'white', 'Greece', 'approved'),
  ('POULSARD NOIR', ARRAY['PLOUSSARD N'], false, 'red', 'France', 'approved'),
  ('POZSONYI', NULL, false, 'white', 'Hungary', 'approved'),
  ('PRACA', NULL, false, 'white', 'Portugal', 'approved'),
  ('PREMETTA', NULL, false, 'red', 'Italy', 'approved'),
  ('PRETO CARDANA', NULL, false, 'red', 'Portugal', 'approved'),
  ('PRETO MARTINHO', NULL, false, 'red', 'Portugal', 'approved'),
  ('PRIETO PICUDO TINTO', NULL, false, 'red', 'Spain', 'approved'),
  ('PRIKNADI', NULL, false, 'white', 'Greece', 'approved'),
  ('PRIMAVERA', NULL, false, 'red', 'Portugal', 'approved'),
  ('PRIMERA', NULL, false, 'white', 'Germany', 'approved'),
  ('PRIMITIVO', ARRAY['BLAUER SCHEUCHNER, ZINFANDEL'], false, 'red', NULL, 'approved'),
  ('PRINZIPAL', NULL, false, 'white', 'Germany', 'approved'),
  ('PRIOR', NULL, false, 'red', 'Germany', 'approved'),
  ('PRODEST', NULL, false, 'red', 'Italy', 'approved'),
  ('PRUNELARD', NULL, false, 'red', 'France', 'approved'),
  ('PRUNESTA', NULL, false, 'red', 'Italy', 'approved'),
  ('PSILOMAVRO KALAVRITON', NULL, false, 'red', 'Greece', 'approved'),
  ('PURPURIU', NULL, true, 'rosé', 'Romania', 'approved'),
  ('QUAGLIANO', NULL, false, 'red', 'Italy', 'approved'),
  ('RABIGATO', NULL, false, 'white', 'Portugal', 'approved'),
  ('RABIGATO MORENO', NULL, false, 'white', 'Portugal', 'approved'),
  ('RABO DE ANHO', NULL, false, 'red', 'Portugal', 'approved'),
  ('RABO DE LOBO', NULL, false, 'red', 'Portugal', 'approved'),
  ('RABO DE OVELHA', NULL, false, 'white', 'Portugal', 'approved'),
  ('RABOSO PIAVE', ARRAY['FRIULARO *'], false, 'red', 'Italy', 'approved'),
  ('RABOSO VERONESE', NULL, false, 'red', 'Italy', 'approved'),
  ('RADAMES', NULL, false, 'red', 'Romania', 'approved'),
  ('RAEUSCHLING WEISS', ARRAY['RäUSCHLING'], false, 'white', NULL, 'approved'),
  ('RAFFIAT DE MONCADE', NULL, false, 'white', 'France', 'approved'),
  ('RALUCA', NULL, false, 'white', 'Romania', 'approved'),
  ('RAMISCO', NULL, false, 'red', 'Portugal', 'approved'),
  ('RATHAY', NULL, false, 'other', 'Austria', 'approved'),
  ('RATINHO', NULL, false, 'white', 'Portugal', 'approved'),
  ('RAVAT BLANC', ARRAY['RAVAT 6'], true, 'white', 'France', 'approved'),
  ('RAYON D''OR', ARRAY['4986 SEIBEL'], true, 'white', 'France', 'approved'),
  ('REBERGER', NULL, false, 'red', 'Germany', 'approved'),
  ('REBO', NULL, false, 'other', 'Bulgaria', 'approved'),
  ('RECANTINA', NULL, false, 'red', 'Italy', 'approved'),
  ('REDORA', NULL, false, 'white', 'Spain', 'approved'),
  ('REFOSCO DAL PEDUNCOLO ROSSO', ARRAY['REFOSCO*', 'MALVOISE* *'], false, 'red', 'Italy', 'approved'),
  ('REFOSCO NOSTRANO', ARRAY['REFOSCO*', 'REFOSCO GROSSO', 'REFOSCONE', 'MALVOISE**'], false, 'red', 'Italy', 'approved'),
  ('REFREN', NULL, true, 'white', 'Hungary', 'approved'),
  ('REGENT', NULL, true, 'red', 'Czech Republic', 'approved'),
  ('REGNER', NULL, false, 'white', 'Germany', 'approved'),
  ('REICHENSTEINER', NULL, false, 'white', 'Germany', 'approved'),
  ('RETAGLIADO BIANCO', NULL, false, 'white', 'Italy', 'approved'),
  ('RHEINFELDER', NULL, false, 'white', 'Germany', 'approved'),
  ('RIBOL', NULL, false, 'red', 'France', 'approved'),
  ('RIBOLLA GIALLA', ARRAY['RIBOLLA', 'RIBUELE', 'REBULA'], false, 'white', 'Italy', 'approved'),
  ('RICOCA', NULL, false, 'red', 'Portugal', 'approved'),
  ('RIESLANER', NULL, false, 'white', 'Germany', 'approved'),
  ('RIESLING ROT', ARRAY['RIESLING', 'RHEINRIESLING', 'RIESLING RENANO'], false, 'red', NULL, 'approved'),
  ('RIESLING WEISS', NULL, false, 'white', 'Hungary', 'approved'),
  ('RIO GRANDE', NULL, false, 'white', 'Portugal', 'approved'),
  ('RKATSITELI', NULL, false, 'white', 'Bulgaria', 'approved'),
  ('ROAL', NULL, false, 'red', 'Portugal', 'approved'),
  ('ROBOLA', NULL, false, 'white', 'Greece', 'approved'),
  ('RODITIS', ARRAY['ALEPOU'], false, 'rosé', 'Greece', 'approved'),
  ('ROESLER', NULL, false, 'other', 'Austria', 'approved'),
  ('ROJAL TINTA', NULL, false, 'red', 'Spain', 'approved'),
  ('ROKANIARIS', NULL, false, 'white', 'Greece', 'approved'),
  ('ROMBOLA KOKKINI', NULL, false, 'red', 'Greece', 'approved'),
  ('ROME', NULL, false, 'red', 'Spain', 'approved'),
  ('ROMEIKO', NULL, false, 'red', 'Greece', 'approved'),
  ('ROMORANTIN', ARRAY['DANERY B'], false, 'white', 'France', 'approved'),
  ('RONDINELLA', NULL, false, 'red', 'Italy', 'approved'),
  ('RONDO', NULL, false, 'red', 'Germany', 'approved'),
  ('ROSCIOLA', NULL, false, 'rosé', 'Italy', 'approved'),
  ('ROSEIRA', NULL, false, 'red', 'Portugal', 'approved'),
  ('ROSINA', NULL, true, 'rosé', 'Romania', 'approved'),
  ('ROSSESE BIANCO', NULL, false, 'white', 'Italy', 'approved'),
  ('ROSSIGNOLA', ARRAY['ROSSETTA'], false, 'red', 'Italy', 'approved'),
  ('ROSSOLA NERA', ARRAY['ROSSOLA'], false, 'red', 'Italy', 'approved'),
  ('ROSSONE', NULL, false, 'red', 'Italy', 'approved'),
  ('ROTBERGER', NULL, false, 'red', 'Germany', 'approved'),
  ('ROTGIPFLER', NULL, false, 'white', 'Czech Republic', 'approved'),
  ('ROUBLOT', NULL, false, 'white', 'France', 'approved'),
  ('ROUPEIRO BRANCO', NULL, false, 'white', 'Portugal', 'approved'),
  ('ROUSSANNE', NULL, false, 'white', 'Italy', 'approved'),
  ('ROUSSANNE DU VAR', ARRAY['ROUSSANNE DU VAR RS'], false, 'rosé', 'France', 'approved'),
  ('ROUSSETTE D''AYZE', NULL, false, 'white', 'France', 'approved'),
  ('ROUSSIN', NULL, false, 'red', 'Italy', 'approved'),
  ('ROVELLO BIANCO', NULL, false, 'white', 'Italy', 'approved'),
  ('ROXO FLOR', NULL, false, 'red', 'Portugal', 'approved'),
  ('ROXO REI', NULL, false, 'red', 'Portugal', 'approved'),
  ('ROZ DE MINIS', NULL, false, 'rosé', 'Romania', 'approved'),
  ('ROZALA BIANCA', NULL, false, 'white', 'Hungary', 'approved'),
  ('ROZSAKOE', NULL, false, 'white', 'Hungary', 'approved'),
  ('RUBILANDE', ARRAY['11803 SEIBEL'], true, 'rosé', 'France', 'approved'),
  ('RUBINET', NULL, false, 'red', NULL, 'approved'),
  ('RUBY CABERNET', NULL, true, 'red', 'Spain', 'approved'),
  ('RUCHE', NULL, false, 'red', 'Italy', 'approved'),
  ('RUFETE', NULL, false, 'red', 'Spain', 'approved'),
  ('RUGGINE', NULL, false, 'white', 'Italy', 'approved'),
  ('RULING', NULL, false, 'white', 'Germany', 'approved'),
  ('RUZZESE', NULL, false, 'white', 'Italy', 'approved'),
  ('SACY', ARRAY['TRESSALLIER B'], false, 'white', 'France', 'approved'),
  ('SAGRANTINO', NULL, false, 'other', 'Bulgaria', 'approved'),
  ('SAINT COME', NULL, false, 'white', 'France', 'approved'),
  ('SAINT LAURENT', NULL, false, 'red', 'Germany', 'approved'),
  ('SAINT MACAIRE', NULL, false, 'red', 'France', 'approved'),
  ('SAINT PIERRE DORE', NULL, false, 'white', 'France', 'approved'),
  ('SAMARRINHO', NULL, false, 'white', 'Portugal', 'approved'),
  ('SAN GIUSEPPE NERO', NULL, false, 'red', 'Italy', 'approved'),
  ('SAN LUNARDO', NULL, false, 'white', 'Italy', 'approved'),
  ('SAN MARTINO', NULL, false, 'red', 'Italy', 'approved'),
  ('SAN MICHELE', NULL, false, 'red', 'Italy', 'approved'),
  ('SANGIOVESE', ARRAY['NIELLUCCIU N'], false, 'red', 'France', 'approved'),
  ('SANTA MARIA', NULL, false, 'white', 'Italy', 'approved'),
  ('SANTARENA', NULL, false, 'red', 'Portugal', 'approved'),
  ('SANTOAL', NULL, false, 'white', 'Portugal', 'approved'),
  ('SAPERAVI', NULL, false, 'red', 'Czech Republic', 'approved'),
  ('SAPHIRA', NULL, false, 'white', 'Germany', 'approved'),
  ('SARBA', NULL, false, 'white', 'Romania', 'approved'),
  ('SAUVIGNON BLANC', ARRAY['SAUVIGNON BLANC'], false, 'white', 'Czech Republic', 'approved'),
  ('SAVAGNIN ROSE', NULL, false, 'rosé', 'France', 'approved'),
  ('SAVVATIANO', ARRAY['DOUMBRENA ASPRI', 'KOUNTOURA ASPRI', 'PERAHORITIKO', 'SAKEIKO'], false, 'white', 'Greece', 'approved'),
  ('SCHEUREBE', NULL, false, 'white', 'Germany', 'approved'),
  ('SCHIAVA GENTILE', ARRAY['SCHIAVA*', 'KLEINVERNATSCH**', 'MITTERVERNATSCH** VERNATSCH**'], false, 'red', 'Italy', 'approved'),
  ('SCHIAVA GRIGIA', ARRAY['SCHIAVA*', 'VERNATSCH**', 'GRAUVERNATSCH **'], false, 'red', 'Italy', 'approved'),
  ('SCHIAVA GROSSA', ARRAY['TROLLINGER', 'VERNATSCH'], false, 'red', 'Germany', 'approved'),
  ('SCHIAVA LOMBARDA', NULL, false, 'red', 'Italy', 'approved'),
  ('SCHIOPPETTINO', NULL, false, 'red', 'Greece', 'approved'),
  ('SCHOENBURGER', NULL, false, 'rosé', 'Germany', 'approved'),
  ('SCIACCARELLO', ARRAY['SCIACCARELLU N'], false, 'red', 'France', 'approved'),
  ('SCIAGLIN', NULL, false, 'white', 'Italy', 'approved'),
  ('SCIASCINOSO', NULL, false, 'red', 'Italy', 'approved'),
  ('SEARA NOVA', NULL, false, 'white', 'Portugal', 'approved'),
  ('SEGALIN', NULL, false, 'red', 'France', 'approved'),
  ('SEINOIR', ARRAY['8745 SEIBEL'], true, 'red', 'France', 'approved'),
  ('SELECT', NULL, false, 'white', 'France', 'approved'),
  ('SELENA', NULL, false, 'rosé', 'Romania', 'approved'),
  ('SEMEBAT', NULL, false, 'red', 'France', 'approved'),
  ('SEMIDANO', NULL, false, 'white', 'Italy', 'approved'),
  ('SEMILAO', NULL, false, 'white', 'Portugal', 'approved'),
  ('SEMILLON', NULL, false, 'white', 'Spain', 'approved'),
  ('SENNEN', NULL, false, 'red', 'Italy', 'approved'),
  ('SEPTIMER', NULL, false, 'rosé', NULL, 'approved'),
  ('SERCEALINHO', NULL, false, 'white', 'Portugal', 'approved'),
  ('SERCIAL', ARRAY['ESGANA CãO'], false, 'white', 'Portugal', 'approved'),
  ('SERENA', NULL, false, 'white', 'Germany', 'approved'),
  ('SERIFIOTIKO', NULL, false, 'red', 'Greece', 'approved'),
  ('SERVANIN', NULL, false, 'red', 'France', 'approved'),
  ('SERVANT', NULL, false, 'white', 'France', 'approved'),
  ('SEYVAL BLANC', NULL, true, 'white', 'Romania', 'approved'),
  ('SEZAO', NULL, false, 'red', 'Portugal', 'approved'),
  ('SGAVETTA', NULL, false, 'red', 'Italy', 'approved'),
  ('SIBERA', NULL, false, 'white', 'Germany', 'approved'),
  ('SIDERITIS', NULL, false, 'rosé', 'Greece', 'approved'),
  ('SIEGERREBE', NULL, false, 'rosé', 'Czech Republic', 'approved'),
  ('SILCHER', NULL, false, 'white', 'Germany', 'approved'),
  ('SILVANER BLAU', ARRAY['SILVANER'], false, 'red', 'Germany', 'approved'),
  ('SILVANER GRUEN', ARRAY['SILVANER', 'SYLVANER'], false, 'white', 'Germany', 'approved'),
  ('SIRIA', NULL, false, 'white', 'Portugal', 'approved'),
  ('SIRIAN', NULL, false, 'rosé', 'Romania', 'approved'),
  ('SIRIO', NULL, false, 'white', 'Italy', 'approved'),
  ('SIRIUS', NULL, false, 'white', 'Germany', 'approved'),
  ('SIROKA MELNISKA', ARRAY['?????? 55'], false, 'red', 'Bulgaria', 'approved'),
  ('SKIADOPOULO', ARRAY['SAHARA'], false, 'white', 'Greece', 'approved'),
  ('SKLAVA', NULL, false, 'white', 'Greece', 'approved'),
  ('SKOPELITIKON', NULL, false, 'red', 'Greece', 'approved'),
  ('SKYLOKLIMA', NULL, false, 'white', 'Greece', 'approved'),
  ('SKYLOPNICHTIS KOKKINOS', NULL, false, 'red', 'Greece', 'approved'),
  ('SLANKAMENKA BELA', NULL, false, 'white', 'Romania', 'approved'),
  ('SOLARIS', NULL, false, 'white', 'Germany', 'approved'),
  ('SOPERGA', NULL, false, 'red', 'Italy', 'approved'),
  ('STAUFER', NULL, false, 'white', 'Germany', 'approved'),
  ('STAVROCHIOTIKO', NULL, false, 'white', 'Greece', 'approved'),
  ('STAVROTO', ARRAY['AMPELAKIOTIKO MAVRO'], false, 'red', 'Greece', 'approved'),
  ('STORGOZIYA', ARRAY['?????????'], true, 'red', 'Bulgaria', 'approved'),
  ('SUGRATHIRTYTWO', NULL, false, 'white', 'Italy', 'approved'),
  ('SULMER', NULL, false, 'red', 'Germany', 'approved'),
  ('SULTANINA', NULL, false, 'white', 'Greece', 'approved'),
  ('SUMOLL', NULL, false, 'red', 'Spain', 'approved'),
  ('SUMOLL BLANCO', NULL, false, 'white', 'Spain', 'approved'),
  ('SUSUMANIELLO', ARRAY['SUSSUMARIELLO'], false, 'red', 'Italy', 'approved'),
  ('SYKIOTIS', NULL, false, 'red', 'Greece', 'approved'),
  ('SYRAH', ARRAY['????'], false, 'red', 'Bulgaria', 'approved'),
  ('SZIREN', NULL, false, 'white', 'Hungary', 'approved'),
  ('TAMAREZ', NULL, false, 'white', 'Portugal', 'approved'),
  ('TAMJANIKA BELA', NULL, false, 'white', 'Romania', 'approved'),
  ('TAMJANIKA CRNA', ARRAY['MOSCATO DELLE ROSE', 'ROSENMUSKATELLER*'], false, 'red', 'Italy', 'approved'),
  ('TANNAT', NULL, false, 'red', 'Bulgaria', 'approved'),
  ('TAUBERSCHWARZ', NULL, false, 'red', 'Germany', 'approved'),
  ('TAURUS', NULL, true, 'white', 'Hungary', 'approved'),
  ('TAZZELENGHE', NULL, false, 'red', 'Italy', 'approved'),
  ('TEINTURIER', NULL, false, 'red', NULL, 'approved'),
  ('TEMPRANILLO TINTO', ARRAY['TINTA RORIZ'], false, 'red', 'Portugal', 'approved'),
  ('TEOULIER NOIR', NULL, false, 'red', 'France', 'approved'),
  ('TERMARINA', NULL, false, 'red', 'Italy', 'approved'),
  ('TEROLDEGO', NULL, false, 'red', 'Italy', 'approved'),
  ('TERRANO', ARRAY['CAGNINA', 'TERAN', 'LAMBRUSCO DAL PEDUNCOLO ROSSO'], false, 'red', 'Italy', 'approved'),
  ('TERRANTES DU DAO', NULL, false, 'white', 'Portugal', 'approved'),
  ('TERRET BLANC', NULL, false, 'white', 'France', 'approved'),
  ('TERRET GRIS', ARRAY['TERRET-BOURRET G'], false, 'white', 'France', 'approved'),
  ('TERRET NOIR', NULL, false, 'red', 'France', 'approved'),
  ('TERZI     1', NULL, false, 'red', 'Italy', 'approved'),
  ('THIAKO', NULL, false, 'red', 'Greece', 'approved'),
  ('THRAPSA', NULL, false, 'red', 'Greece', 'approved'),
  ('TIBOUREN', NULL, false, 'red', 'Bulgaria', 'approved'),
  ('TIMORASSO', NULL, false, 'white', 'Italy', 'approved'),
  ('TINTA AGUIAR', NULL, false, 'red', 'Portugal', 'approved'),
  ('TINTA AURELIO', NULL, false, 'red', 'Portugal', 'approved'),
  ('TINTA BARROCA', NULL, false, 'red', 'Portugal', 'approved'),
  ('TINTA CARVALHA', NULL, false, 'red', 'Portugal', 'approved'),
  ('TINTA DA GRACIOSA', NULL, false, 'red', 'Portugal', 'approved'),
  ('TINTA DE LISBOA', NULL, false, 'red', 'Portugal', 'approved'),
  ('TINTA DE TABUACO', NULL, false, 'red', 'Portugal', 'approved'),
  ('TINTA FRANCISCA', NULL, false, 'red', 'Portugal', 'approved'),
  ('TINTA MARTINS', NULL, false, 'red', 'Portugal', 'approved'),
  ('TINTA MESQUITA', NULL, false, 'red', 'Portugal', 'approved'),
  ('TINTA PEREIRA', NULL, false, 'red', 'Portugal', 'approved'),
  ('TINTA POMAR', NULL, false, 'red', 'Portugal', 'approved'),
  ('TINTO CAO', NULL, false, 'red', 'Spain', 'approved'),
  ('TINTO DE LA PAMPANA BLANCA', NULL, false, 'red', 'Spain', 'approved'),
  ('TINTO DE PEGOES', NULL, false, 'red', 'Portugal', 'approved'),
  ('TINTO SEM NOME', NULL, false, 'red', 'Portugal', 'approved'),
  ('TINTO VELASCO', ARRAY['FRASCO'], false, 'red', 'Spain', 'approved'),
  ('TORTOSI', NULL, false, 'white', 'Spain', 'approved'),
  ('TOURBAT', NULL, false, 'white', 'Italy', 'approved'),
  ('TOURIGA FEMEA', NULL, false, 'red', 'Portugal', 'approved'),
  ('TOURIGA FRANCA', NULL, false, 'red', 'Portugal', 'approved'),
  ('TOURIGA NACIONAL', NULL, false, 'red', 'Spain', 'approved'),
  ('TOURKOPOULA', NULL, false, 'rosé', 'Greece', 'approved'),
  ('TRAJADURA', NULL, false, 'white', 'Portugal', 'approved'),
  ('TRANSANCORA', NULL, false, 'red', 'Portugal', 'approved'),
  ('TREBBIANINA', NULL, false, 'white', 'Italy', 'approved'),
  ('TREBBIANO GIALLO', ARRAY['ROSSETTO', 'TREBBIANO*'], false, 'white', 'Italy', 'approved'),
  ('TREBBIANO MODENESE', NULL, false, 'white', 'Italy', 'approved'),
  ('TREBBIANO ROMAGNOLO', NULL, false, 'white', 'Italy', 'approved'),
  ('TREBBIANO SPOLETINO', NULL, false, 'white', 'Italy', 'approved'),
  ('TREBBIANO TOSCANO', ARRAY['BIANCHELLO', 'PROCANICO', 'UGNI BLANC *'], false, 'white', 'Italy', 'approved'),
  ('TREPAT', ARRAY['BONICAIRE', 'EMBOLICAIRE'], false, 'red', 'Spain', 'approved'),
  ('TRESSOT NOIR', NULL, false, 'red', 'France', 'approved'),
  ('TREVISANA NERA', NULL, false, 'red', 'Italy', 'approved'),
  ('TRIGUEIRA', NULL, false, 'red', 'Portugal', 'approved'),
  ('TRILLA', NULL, false, 'white', 'Hungary', 'approved'),
  ('TRINCADEIRA', ARRAY['TINTA AMARELA'], false, 'red', 'Portugal', 'approved'),
  ('TRINCADEIRA BRANCA', NULL, false, 'white', 'Portugal', 'approved'),
  ('TRINCADEIRA DAS PRATAS', NULL, false, 'white', 'Portugal', 'approved'),
  ('TRIUNFO', NULL, false, 'red', 'Portugal', 'approved'),
  ('TRONTO', NULL, false, 'red', 'Italy', 'approved'),
  ('TROUSSEAU NOIR', NULL, false, 'red', 'Portugal', 'approved'),
  ('TSAOUSSI', NULL, false, 'white', 'Greece', 'approved'),
  ('TSAPOURNO', NULL, false, 'red', 'Greece', 'approved'),
  ('TURAN', NULL, false, 'red', 'Hungary', 'approved'),
  ('TURCHETTA', NULL, false, 'red', 'Italy', 'approved'),
  ('UCELUT', NULL, false, 'white', 'Italy', 'approved'),
  ('UNIREA', NULL, false, 'white', 'Romania', 'approved'),
  ('UVA CAO', NULL, false, 'white', 'Portugal', 'approved'),
  ('UVA CAVACO', NULL, false, 'white', 'Portugal', 'approved'),
  ('UVA DEL TUNDE', NULL, false, 'red', 'Italy', 'approved'),
  ('UVA DI TROIA', ARRAY['SUMARELLO', 'SOMMARRELLO', 'NERO DI TROIA'], false, 'red', 'Italy', 'approved'),
  ('UVA LONGANESI', NULL, false, 'red', 'Italy', 'approved'),
  ('UVA RARA', NULL, false, 'red', 'Italy', 'approved'),
  ('UVA TOSCA', NULL, false, 'red', 'Italy', 'approved'),
  ('UVALINO', NULL, false, 'red', 'Italy', 'approved'),
  ('VAFTRA', ARRAY['VAPSA'], false, 'red', 'Greece', 'approved'),
  ('VAFTRA ASPRI', NULL, false, 'white', 'Greece', 'approved'),
  ('VALAITIS', NULL, false, 'white', 'Greece', 'approved'),
  ('VALBOM', NULL, false, 'red', 'Portugal', 'approved'),
  ('VALDIGUIE', NULL, false, 'red', 'France', 'approved'),
  ('VALDOSA', NULL, false, 'red', 'Portugal', 'approved'),
  ('VALENTINO NERO', NULL, false, 'red', 'Italy', 'approved'),
  ('VALERIA', NULL, false, 'white', 'Romania', 'approved'),
  ('VALERIEN', NULL, true, 'white', 'Romania', 'approved'),
  ('VALVEIRINHO', NULL, false, 'white', 'Portugal', 'approved'),
  ('VAREJOA', NULL, false, 'red', 'Portugal', 'approved'),
  ('VAROUSSET', ARRAY['23657 SEYVE-VILLARD'], true, 'red', 'France', 'approved'),
  ('VEGA', NULL, false, 'white', 'Italy', 'approved'),
  ('VELTLINER FRUEHROT', ARRAY['FRüHER MALVASIER', 'MALVASIER', 'MALVOISIE'], false, 'red', 'Germany', 'approved'),
  ('VELTLINER GRUEN', NULL, false, 'white', 'Bulgaria', 'approved'),
  ('VELTLINER ROT', NULL, false, 'white', 'Hungary', 'approved'),
  ('VERDEA', NULL, false, 'white', 'Greece', 'approved'),
  ('VERDEJO BLANCO', NULL, false, 'white', 'Spain', 'approved'),
  ('VERDELHO BRANCO', NULL, false, 'white', 'Bulgaria', 'approved'),
  ('VERDELHO ROXO', NULL, false, 'red', 'Portugal', 'approved'),
  ('VERDELHO TINTO', NULL, false, 'red', 'Portugal', 'approved'),
  ('VERDESE', NULL, false, 'white', 'Italy', 'approved'),
  ('VERDESSE', NULL, false, 'white', 'France', 'approved'),
  ('VERDIAL TINTO', NULL, false, 'red', 'Portugal', 'approved'),
  ('VERDICCHIO BIANCO', NULL, false, 'white', 'Greece', 'approved'),
  ('VERDIL', NULL, false, 'white', 'Spain', 'approved'),
  ('VERDISO', NULL, false, 'white', 'Italy', 'approved'),
  ('VERDOT PETIT', ARRAY['???? ?????'], false, 'red', 'Bulgaria', 'approved'),
  ('VERDUZZO FRIULANO', NULL, false, 'white', 'Italy', 'approved'),
  ('VERDUZZO TREVIGIANO', NULL, false, 'white', 'Italy', 'approved'),
  ('VERITAS', NULL, false, 'white', 'Czech Republic', 'approved'),
  ('VERMENTINO', NULL, false, 'white', 'Italy', 'approved'),
  ('VERMENTINO NERO', NULL, false, 'red', 'Italy', 'approved'),
  ('VERNACCIA BIANCA', NULL, false, 'white', 'Bulgaria', 'approved'),
  ('VERNACCIA DI ORISTANO', NULL, false, 'white', 'Italy', 'approved'),
  ('VERNACCIA DI SAN GIMIGNANO', NULL, false, 'white', 'Italy', 'approved'),
  ('VERNACCIA NERA', ARRAY['VERNACCIA*'], false, 'red', 'Italy', 'approved'),
  ('VERTZAMI', NULL, false, 'red', 'Greece', 'approved'),
  ('VERTZAMI LEFKO', NULL, false, 'white', 'Greece', 'approved'),
  ('VERUCCESE', NULL, false, 'red', 'Italy', 'approved'),
  ('VESPAIOLA', ARRAY['VESPAIOLO*'], false, 'white', 'Italy', 'approved'),
  ('VESPOLINA', ARRAY['UGHETTA'], false, 'red', 'Italy', 'approved'),
  ('VIDADILLO', NULL, false, 'red', 'Spain', 'approved'),
  ('VIDIANO', NULL, false, 'white', 'Greece', 'approved'),
  ('VIEN DE NUS', NULL, false, 'red', 'Italy', 'approved'),
  ('VIJARIEGO BLANCO', ARRAY['BUJARIEGO', 'DIEGO', 'BIGIRIEGO'], false, 'white', 'Spain', 'approved'),
  ('VILANA', NULL, false, 'white', 'Greece', 'approved'),
  ('VILAROM', NULL, false, 'white', 'Romania', 'approved'),
  ('VILLARD BLANC', ARRAY['12375 SEYVE-VILLARD'], true, 'white', 'France', 'approved'),
  ('VILLARD NOIR', ARRAY['18315 SEYVE-VILLARD'], true, 'red', 'France', 'approved'),
  ('VILLARIS', NULL, false, 'white', 'Germany', 'approved'),
  ('VINHAO', ARRAY['LOUREIRO TINTO'], false, 'red', 'Spain', 'approved'),
  ('VIOGNIER', NULL, false, 'white', 'Spain', 'approved'),
  ('VIOLENTO', NULL, false, 'red', 'Greece', 'approved'),
  ('VIOSINHO', NULL, false, 'white', 'Portugal', 'approved'),
  ('VIRGILIO', NULL, false, 'red', 'Italy', 'approved'),
  ('VITAL', NULL, false, 'white', 'Portugal', 'approved'),
  ('VIURA', ARRAY['VIURA'], false, 'white', 'Spain', 'approved'),
  ('VLACHIKO', NULL, false, 'red', 'Greece', 'approved'),
  ('VOIDOMATIS', NULL, false, 'red', 'Greece', 'approved'),
  ('VOIDOMATIS ASPROS', NULL, false, 'white', 'Greece', 'approved'),
  ('VOLITSA ASPRI', NULL, false, 'white', 'Greece', 'approved'),
  ('VOLITSA MAVRI', NULL, false, 'red', 'Greece', 'approved'),
  ('VRADIANO', NULL, false, 'red', 'Greece', 'approved'),
  ('VRBOSKA', NULL, false, 'rosé', 'Czech Republic', 'approved'),
  ('VUILLERMIN', NULL, false, 'red', 'Italy', 'approved'),
  ('WELSCHRIESLING', ARRAY['??????? ??????????'], false, 'white', 'Bulgaria', 'approved'),
  ('WILDBACHER BLAU', NULL, false, 'other', 'Austria', 'approved'),
  ('WUERZER', NULL, false, 'white', 'Germany', 'approved'),
  ('XARA', NULL, false, 'red', 'Portugal', 'approved'),
  ('XARELLO', ARRAY['CARTOIXA', 'PANSA BLANCA', 'PANSAL', 'XAREL-LO'], false, 'white', 'Spain', 'approved'),
  ('XARELLO ROSADO', ARRAY['PANSA ROSADA'], false, 'white', 'Spain', 'approved'),
  ('XYNOMAVRO', ARRAY['XINOGALTSO', 'POPOLKA', 'MAVRO NAOUSIS**'], false, 'red', 'Greece', 'approved'),
  ('ZALA GYOENGYE', NULL, true, 'white', NULL, 'approved'),
  ('ZALEMA', NULL, false, 'white', 'Spain', 'approved'),
  ('ZALOVITIKO', NULL, false, 'red', 'Greece', 'approved'),
  ('ZE DO TELHEIRO', NULL, false, 'red', 'Portugal', 'approved'),
  ('ZEFIR', NULL, false, 'white', 'Hungary', 'approved'),
  ('ZENGOE', NULL, false, 'white', 'Hungary', 'approved'),
  ('ZENIT', NULL, false, 'white', 'Hungary', 'approved'),
  ('ZETA', NULL, false, 'white', 'Hungary', 'approved'),
  ('ZEUSZ', NULL, false, 'white', 'Hungary', 'approved'),
  ('ZIERFANDLER ROT', ARRAY['SPäTROT'], false, 'other', 'Austria', 'approved'),
  ('ZIERFANDLER WEISS', NULL, false, 'white', 'Hungary', 'approved'),
  ('ZLATARICA VRGORSKA', ARRAY['FRANCAVILLA'], false, 'white', 'Italy', 'approved'),
  ('ZWEIGELTREBE BLAU', ARRAY['ROTBURGER', 'ZWEIGELT', 'ZWEIGELTREBE'], false, 'red', 'Germany', 'approved')
ON CONFLICT (LOWER(name)) DO UPDATE SET
  synonyms = EXCLUDED.synonyms,
  piwi = EXCLUDED.piwi,
  color = EXCLUDED.color,
  origin_country = EXCLUDED.origin_country
WHERE varieties.status = 'review_needed';

-- Re-run curated seed (adds varieties not in VIVC catalog)
-- Note: ON CONFLICT (LOWER(name)) DO NOTHING ensures no duplicates
\i seeds/001_varieties.sql
